In [52]:
import pandas as pd
import numpy as np

df= pd.read_csv("C:\\Users\\bhoom\\Downloads\\test-data.csv")
df

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
0,0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN
1,1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN
2,2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0,25.27 Lakh
3,3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0,NaN
4,4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229,1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN
1230,1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN
1231,1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN
1232,1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN
1233,1233,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1234 non-null   int64
 1   Name               1234 non-null   object
 2   Location           1234 non-null   object
 3   Year               1234 non-null   int64
 4   Kilometers_Driven  1234 non-null   int64
 5   Fuel_Type          1234 non-null   object
 6   Transmission       1234 non-null   object
 7   Owner_Type         1234 non-null   object
 8   Mileage            1234 non-null   object
 9   Engine             1224 non-null   object
 10  Power              1224 non-null   object
 11  Seats              1223 non-null   float64
 12  New_Price          182 non-null    object
dtypes: float64(1), int64(3), object(9)
memory usage: 125.5+ KB

In [54]:
df=df.drop("Unnamed: 0", axis = 1)

In [55]:
df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price'],
      dtype='object')

In [56]:
df.columns.value_counts()

Name                 1
Location             1
Year                 1
Kilometers_Driven    1
Fuel_Type            1
Transmission         1
Owner_Type           1
Mileage              1
Engine               1
Power                1
Seats                1
New_Price            1
Name: count, dtype: int64

In [57]:
df.duplicated().sum()

np.int64(1)

In [58]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN
1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN
2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0,25.27 Lakh
3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0,NaN
4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN
1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN
1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN
1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN
1233,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN

In [59]:
df["New_Price"].isna().sum()

np.int64(1052)

In [60]:
df=df.drop("New_Price",axis=1)

In [61]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0
1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0
2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0
3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0
4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0
...,...,...,...,...,...,...,...,...,...,...,...
1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0
1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0
1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0
1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0
1233,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0

In [62]:
df.isna().sum()

Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               0
Engine               10
Power                10
Seats                11
dtype: int64

## Name

In [63]:
df["Name"].isna().sum()

np.int64(0)

In [64]:
df["Name"].unique()

array(['Maruti Alto K10 LXI CNG', 'Maruti Alto 800 2016-2019 LXI',
       'Toyota Innova Crysta Touring Sport 2.4 MT',
       'Toyota Etios Liva GD', 'Hyundai i20 Magna',
       'Mahindra XUV500 W8 2WD', 'Toyota Fortuner 4x2 AT TRD Sportivo',
       'Hyundai EON Era Plus', 'Honda City 1.5 S MT',
       'Mahindra XUV500 W6 2WD', 'Audi Q5 2008-2012 2.0 TDI',
       'Hyundai Grand i10 Magna', 'Toyota Corolla H5',
       'Maruti Swift Vdi BSIII', 'Nissan Terrano XL', 'BMW X1 sDrive20d',
       'BMW 3 Series GT 320d Luxury Line', 'Ford Ikon 1.4 TDCi DuraTorq',
       'Maruti Swift AMT ZXI', 'Maruti Swift Dzire VXi',
       'Maruti Ritz LDi', 'Nissan Micra XV',
       'Skoda Laura 1.8 TSI Ambition',
       'Honda Civic 2010-2013 1.8 S MT Inspire', 'Ford Ikon 1.3 Flair',
       'Maruti Alto LX', 'Honda Jazz 1.5 V i DTEC',
       'Skoda Rapid 1.5 TDI AT Ambition', 'Hyundai i20 1.2 Sportz',
       'Toyota Etios Cross 1.4L VD', 'Volkswagen Polo GT TDI',
       'Hyundai i10 Era 1.1 iTech SE', 'Mitsubishi Pajero 2.8 SFX',
       'Maruti Swift Dzire Tour LDI', 'Maruti Swift Dzire VXI',
       'Skoda Rapid 1.6 MPI AT Style',
       'Hyundai Creta 1.6 SX Plus Dual Tone Petrol',
       'Toyota Innova 2.5 G (Diesel) 7 Seater BS IV',
       'BMW 5 Series 520d Luxury Line', 'Maruti Baleno Alpha 1.3',
       'Audi A4 2.0 TDI 177 Bhp Technology Edition',
       'Audi A4 2.0 TDI Multitronic', 'Skoda Rapid 1.6 MPI Ambition',
       'Maruti Ertiga SHVS VDI', 'Maruti Ciaz 1.4 Zeta',
       'Maruti Ciaz ZXi', 'Mercedes-Benz A Class A200 CDI Sport',
       'Toyota Innova 2.5 ZX Diesel 7 Seater',
       'BMW 3 Series 320d Prestige', 'Ford Ecosport 1.5 DV5 MT Titanium',
       'Ford Endeavour 3.0L 4X4 AT', 'Audi Q5 2.0 TDI',
       'Hyundai Verna 1.6 SX VTVT', 'Mahindra XUV500 W8 4WD',
       'Maruti Vitara Brezza ZDi', 'Toyota Etios Liva 1.4 VXD',
       'Tata Indigo CS LX (TDI) BS III', 'Honda City ZX GXi',
       'Toyota Corolla Altis G', 'Hyundai Grand i10 Asta',
       'Hyundai i20 Sportz 1.2', 'Volkswagen Polo 1.5 TDI Comfortline',
       'Maruti Celerio X VXI Option', 'Chevrolet Sail Hatchback 1.2',
       'Mahindra Scorpio VLX Special Edition BS-IV',
       'Volkswagen Ameo 1.5 TDI Comfortline', 'Maruti Wagon R LXI',
       'Honda Brio S Option MT', 'Maruti Ertiga VXI',
       'Hyundai Santro Xing GL', 'Ford Figo Aspire 1.2 Ti-VCT Titanium',
       'Tata Tiago AMT 1.2 Revotron XTA', 'Hyundai Santro Xing XL',
       'Chevrolet Beat LT', 'Nissan Micra Diesel XV',
       'Toyota Innova 2.5 GX (Diesel) 8 Seater',
       'Hyundai Xcent 1.2 VTVT E', 'Maruti Ciaz VXi',
       'BMW 5 Series 2013-2017 520d Luxury Line',
       'Toyota Camry Hybrid 2.5', 'Toyota Corolla Altis D-4D G',
       'Hyundai Verna 1.6 SX CRDi (O)',
       'Volkswagen Vento 1.5 TDI Highline AT', 'Nissan Teana XL',
       'Hyundai i20 1.2 Sportz Option',
       'Tata Manza Club Class Safire90 LX', 'Ford Figo Diesel ZXI',
       'Hyundai i20 Asta 1.2', 'Ford Fiesta Classic 1.6 SXI Duratec',
       'Mercedes-Benz B Class B180 Sports', 'Maruti Swift Dzire VDI',
       'Hyundai Santro Xing GLS', 'Maruti Baleno Alpha',
       'Honda Accord 2.4 Elegance M/T', 'Nissan Micra XL CVT',
       'Maruti Zen Estilo LXI BS IV', 'Hyundai Elantra CRDi SX',
       'Tata Indica V2 DiCOR DLG BS-III', 'Tata Nano Lx',
       'Honda Amaze S i-Dtech', 'Volkswagen Polo Diesel Highline 1.2L',
       'Tata Indica Vista Quadrajet LX', 'Audi Q3 30 TDI S Edition',
       'Honda City i DTEC SV', 'Honda Amaze SX i-DTEC',
       'Hyundai i20 Asta Option 1.2', 'Honda Brio S MT',
       'Mercedes-Benz New C-Class C 250 CDI Avantgarde',
       'Volkswagen Polo 1.2 MPI Highline', 'Hyundai i10 Magna AT',
       'Hyundai i20 1.2 Magna Executive', 'BMW 5 Series 525d Sedan',
       'Maruti Swift Dzire Vdi BSIV', 'Honda BRV i-DTEC V MT',
       'Maruti Swift Dzire VDI Optional', 'BMW X3 xDrive20d',
       'Chevrolet Beat Diesel LS', 'Audi Q3 30 TDI Premium FWD',
       'Mercedes-Benz GL-Class 2007 2012 350 CDI Luxury',
       'BMW 3 Series GT 320d Sport Line', 'Hyundai Grand i10 Asta Option',
       'Toyota Etios Liva VD', 'Datsun GO T Petrol',
       'Maruti Ignis 1.2 Alpha', 'Maruti A-Star Zxi',
       'Honda Civic 2010-2013 1.8 V AT Sunroof', 'Maruti Alto 800 LXI',
       'Jaguar XE 2.0L Diesel Prestige', 'Hyundai i20 1.4 CRDi Sportz',
       'Ford EcoSport 1.0 Ecoboost Titanium Plus',
       'Mahindra KUV 100 mFALCON G80 K4 5str',
       'Maruti Vitara Brezza VDi Option',
       'Volkswagen Vento Diesel Highline', 'Ford Fiesta 1.4 SXI Duratorq',
       'Fiat Avventura FIRE Dynamic', 'Honda Civic 2006-2010 1.8 V MT',
       'Honda CR-V Diesel', 'Hyundai i10 Magna',
       'Volkswagen Ameo 1.5 TDI Highline AT', 'Hyundai Accent CRDi',
       'Ford Ecosport 1.5 DV5 MT Titanium Optional',
       'Jaguar XF 2.2 Litre Luxury', 'Maruti Baleno Alpha 1.2',
       'Hyundai Grand i10 CRDi Magna', 'Hyundai EON Era',
       'Mercedes-Benz E-Class 2015-2017 E250 Edition E',
       'Mercedes-Benz M-Class ML 350 4Matic',
       'Ford EcoSport 1.5 Diesel Titanium', 'Maruti Celerio VXI AT',
       'Mahindra Xylo E9', 'Hyundai Creta 1.6 SX Automatic',
       'Honda Mobilio V i VTEC',
       'Mercedes-Benz GL-Class 350 CDI Blue Efficiency',
       'Mercedes-Benz S Class 2005 2013 S 350 L',
       'Volkswagen Vento 1.5 TDI Highline',
       'Mercedes-Benz E-Class E250 CDI Avantgrade', 'Toyota Etios V',
       'Tata Indica Vista Aqua TDI BSIII', 'Volkswagen Passat 1.8 TSI MT',
       'Maruti Alto LXi', 'Skoda Laura 1.9 TDI MT Elegance',
       'Maruti Wagon R LX', 'Nissan Sunny 2011-2014 Diesel XV',
       'Honda Brio VX', 'Hyundai i10 Sportz',
       'Mercedes-Benz M-Class ML 250 CDI',
       'Volkswagen Vento Petrol Comfortline', 'Honda Mobilio S i DTEC',
       'Maruti Alto LXI', 'Honda City ZX VTEC Plus',
       'Audi A8 L 3.0 TDI quattro', 'Maruti Swift Dzire VDi',
       'Hyundai Verna CRDi ABS', 'Tata Indica DLS', 'Tata Nano XT',
       'BMW 7 Series 730Ld DPE Signature', 'Honda Brio 1.2 S MT',
       'Hindustan Motors Contessa 2.0 DSL',
       'Renault Duster 110PS Diesel RxZ', 'Maruti Dzire ZDI',
       'Honda City i VTEC V', 'Jaguar XF Diesel',
       'BMW 3 Series 320d Luxury Line', 'BMW 3 Series Luxury Line',
       'Mercedes-Benz New C-Class C 220d Avantgarde Edition C',
       'Maruti Omni E 8 Str STD', 'Volkswagen Vento Petrol Highline',
       'Audi A6 2011-2015 2.0 TDI Premium Plus', 'Fiat Linea Dynamic',
       'Hyundai Verna 1.6 SX', 'Hyundai i20 Active 1.2 S',
       'Honda Brio V MT', 'Honda Mobilio RS Option i DTEC',
       'Mitsubishi Pajero Sport 4X4',
       'Tata Manza Club Class Quadrajet90 LS',
       'Renault Duster Adventure Edition',
       'Hyundai Verna CRDi 1.6 AT SX Plus', 'Maruti Ritz VDi',
       'Toyota Innova 2.5 V Diesel 8-seater',
       'Tata Sumo EX 10/7 Str BSII',
       'Audi Q3 35 TDI Quattro Premium Plus',
       'Fiat Grande Punto 1.2 Emotion', 'Hyundai Elantra SX',
       'Volkswagen Polo Diesel Trendline 1.2L',
       'Toyota Etios Cross 1.2L G', 'Mahindra Scorpio S4 7 Seater',
       'Maruti Ciaz VXi Plus', 'Ford Figo Petrol Titanium',
       'Mini Cooper S', 'Hyundai Creta 1.6 CRDi SX',
       'Mahindra Thar CRDe AC', 'Hyundai i10 Sportz 1.1L',
       'Maruti Wagon R LXI DUO BSIII', 'Maruti Baleno Delta CVT',
       'Maruti Alto LX BSIII', 'Hyundai Xcent 1.2 Kappa S Option',
       'Toyota Corolla Altis Diesel D4DG',
       'Volkswagen Polo Petrol Highline 1.2L', 'Hyundai i10 Era',
       'Hyundai Grand i10 1.2 Kappa Sportz',
       'Hyundai Verna 1.6 SX VTVT (O) AT', 'Ford Fiesta 1.4 SXi TDCi ABS',
       'Tata Xenon XT EX 4X2', 'Maruti Alto K10 2010-2014 VXI',
       'Audi A6 2011-2015 35 TDI Premium',
       'Renault Duster 85PS Diesel RxL Optional', 'Mahindra Thar 4X4',
       'Toyota Innova 2.5 GX (Diesel) 7 Seater', 'Chevrolet Aveo 1.6 LT',
       'Toyota Etios GD', 'Jaguar XE Portfolio',
       'Chevrolet Aveo U-VA 1.2 LS', 'Maruti Swift VDI BSIV',
       'Mercedes-Benz E-Class 2009-2013 E250 CDI Avantgarde',
       'Hyundai Accent GLE 1', 'Audi A4 New 2.0 TDI Multitronic',
       'Chevrolet Tavera LS B3 10 Seats BSIII',
       'Mahindra Xylo E8 ABS BS IV', 'Hyundai i20 Active SX Diesel',
       'Mercedes-Benz New C-Class 220 CDI AT',
       'Skoda Superb Elegance 1.8 TSI AT', 'Skoda Rapid 1.5 TDI Elegance',
       'Mercedes-Benz E-Class 2009-2013 E200 CGI Blue Efficiency',
       'Maruti 800 AC', 'Maruti Swift LDI', 'Honda BR-V i-DTEC S MT',
       'Audi A6 2011-2015 2.0 TDI Technology',
       'Toyota Fortuner 3.0 Diesel', 'Toyota Camry MT with Moonroof',
       'Maruti Ignis 1.2 Delta', 'Hyundai Verna 1.6 VTVT S',
       'Honda City V MT', 'Honda City 1.5 E MT',
       'Mahindra Verito 1.5 D4 BSIV', 'Hyundai EON D Lite Plus',
       'Toyota Innova 2.5 G (Diesel) 8 Seater', 'Maruti Ertiga VDI',
       'Audi Q7 3.0 TDI Quattro Premium Plus', 'Maruti Alto K10 LXI',
       'Tata Indica V2 eLX',
       'Mercedes-Benz New C-Class C 220 CDI Avantgarde',
       'Honda City 1.5 V MT', 'Toyota Innova 2.5 VX (Diesel) 7 Seater',
       'Hyundai i20 1.2 Magna',
       'Mercedes-Benz E-Class 2009-2013 E250 CDI Blue Efficiency',
       'Honda Accord VTi-L (AT)', 'Toyota Innova Crysta 2.4 ZX MT',
       'Hyundai i20 Asta Option 1.4 CRDi',
       'Mahindra Verito Vibe 1.5 dCi D6', 'Maruti Eeco 5 Seater AC',
       'Toyota Corolla Altis 1.8 G', 'Toyota Corolla Altis VL AT',
       'Mercedes-Benz A Class A180 Sport', 'Hyundai i20 Asta 1.4 CRDi',
       'Honda Accord 2.4 M/T', 'Honda Accord 2.4 AT',
       'Mahindra Bolero SLE BSIII', 'Honda Amaze S i-Vtech',
       'Volkswagen Jetta 2007-2011 1.6 Trendline', 'Ford Figo Petrol ZXI',
       'Toyota Innova 2.5 G (Diesel) 7 Seater',
       'Hyundai Elite i20 Asta Option', 'Mahindra KUV 100 mFALCON D75 K2',
       'Bentley Flying Spur W12', 'Toyota Fortuner 2.8 2WD MT',
       'Tata Indica V2 DLS BSIII', 'Nissan Micra Active XV',
       'Hyundai Grand i10 Sportz', 'Tata Tigor 1.2 Revotron XZ Option',
       'Honda Accord 2001-2003 2.3 VTI L MT', 'Mahindra Xylo E4',
       'Land Rover Freelander 2 S Business Edition',
       'Tata Indigo eCS eLX BS IV', 'Fiat Linea Emotion (Diesel)',
       'Tata Tiago 1.2 Revotron XZ',
       'Volkswagen Polo Diesel Comfortline 1.2L',
       'Maruti Wagon R VXI BS IV', 'Hyundai Creta 1.6 CRDi AT SX Plus',
       'Audi A4 35 TDI Technology', 'BMW X1 xDrive 20d xLine',
       'Ford Endeavour 3.0L AT 4x2', 'Maruti Vitara Brezza LDi',
       'Mercedes-Benz New C-Class 200 K AT',
       'Volvo XC90 2007-2015 D5 AWD', 'Nissan Teana 230jM',
       'Hyundai Santro Xing GLS CNG', 'BMW X6 xDrive30d',
       'Tata Indigo CS eVX', 'Audi Q5 30 TDI quattro Premium Plus',
       'Hyundai i10 Sportz 1.2', 'Maruti Baleno Delta 1.2',
       'Maruti Swift VDI', 'Toyota Land Cruiser Prado VX L',
       'Hyundai Tucson 2.0 e-VGT 4WD AT GLS', 'Maruti Baleno Delta',
       'Audi A4 2.0 TDI', 'Maruti Dzire AMT ZXI Plus',
       'Toyota Innova 2.5 GX 8 STR', 'Maruti Wagon R VXI AMT Opt',
       'Skoda Laura L and K MT', 'Maruti Swift LXI Option',
       'Maruti Omni MPI CARGO BSIV', 'Honda Amaze S AT i-Vtech',
       'Toyota Corolla H2', 'Chevrolet Spark 1.0 LT',
       'Audi Q3 2012-2015 2.0 TDI Quattro Premium Plus',
       'Chevrolet Cruze LTZ AT', 'Hyundai Xcent 1.2 Kappa AT SX Option',
       'Nissan Terrano XV D Pre', 'Ford Ecosport 1.5 DV5 MT Ambiente',
       'Land Rover Range Rover HSE', 'Toyota Etios G',
       'Volkswagen Polo ALLSTAR 1.2 MPI',
       'Toyota Innova 2.5 VX (Diesel) 7 Seater BS IV',
       'Hyundai Verna CRDi 1.6 SX Option',
       'Land Rover Discovery 4 SDV6 SE', 'Honda City i DTec VX Option BL',
       'Nissan Micra XV CVT', 'Hyundai Santro GLS I - Euro II',
       'Maruti Vitara Brezza ZDi Plus Dual Tone', 'Honda Accord 2.4 A/T',
       'Maruti Swift VDI BSIV W ABS',
       'Mercedes-Benz GLC 220d 4MATIC Sport', 'Mahindra Xylo D4 BSIV',
       'Datsun GO Plus T Petrol', 'Maruti SX4 VDI', 'Maruti Celerio VXI',
       'Volkswagen Vento 1.5 TDI Comfortline AT',
       'Ford EcoSport 1.5 TDCi Titanium',
       'Hyundai Santro LS zipDrive Euro I', 'Honda Brio VX AT',
       'Mitsubishi Pajero Sport 4X2 AT', 'Maruti Swift VDI Optional',
       'Hyundai Accent GLE', 'BMW 3 Series 320d Sport',
       'Renault KWID Climber 1.0 AMT', 'Mahindra Bolero VLX CRDe',
       'Hyundai Creta 1.6 SX Diesel',
       'Volkswagen Passat Diesel Highline 2.0 TDI',
       'Isuzu MU 7 4x2 HIPACK',
       'Mercedes-Benz E-Class 2015-2017 E250 CDI Avantgarde',
       'Nissan Sunny 2011-2014 XL', 'Hyundai Elantra GT',
       'Honda Accord VTi-L AT', 'Toyota Fortuner 4x4 MT',
       'Mini Cooper 3 DOOR D', 'Chevrolet Beat LS',
       'Mercedes-Benz B Class B180 Sport',
       'Audi Q5 2008-2012 2.0 TFSI Quattro',
       'Skoda Laura 1.9 TDI AT Ambiente',
       'Hyundai Creta 1.6 CRDi SX Option', 'BMW 7 Series 730Ld',
       'Skoda Laura Ambiente 2.0 TDI CR AT', 'Hyundai i20 1.4 CRDi Magna',
       'Maruti A-Star AT Vxi Aktiv', 'Hyundai Verna 1.6 VTVT',
       'BMW 3 Series 320d', 'Maruti Zen Estilo VXI BSIII',
       'Audi Q3 2012-2015 35 TDI Quattro Premium', 'Honda Brio E MT',
       'Mahindra Bolero SLX', 'Maruti Celerio ZDi', 'Hyundai Getz GVS',
       'Hyundai Xcent 1.2 CRDi SX',
       'Ford EcoSport 1.5 Ti VCT AT Titanium',
       'BMW 5 Series 530i Sport Line', 'Maruti Wagon R VXI 1.2',
       'Chevrolet Optra Magnum 2.0 LT', 'Renault KWID RXL',
       'Volkswagen Jetta 2013-2015 2.0L TDI Highline',
       'Ford Figo Diesel Titanium', 'Chevrolet Spark 1.0 LS',
       'Honda Jazz VX CVT', 'Chevrolet Cruze LTZ',
       'Skoda Rapid 1.6 MPI AT Style Plus', 'Maruti Ritz ZXi',
       'Honda City 1.5 S AT', 'Tata Indica Vista Aqua 1.2 Safire',
       'Toyota Etios Liva Diesel TRD Sportivo',
       'Skoda Rapid Ultima 1.6 TDI Ambition Plus', 'Maruti SX4 ZXI AT',
       'Hyundai i20 new Sportz AT 1.4',
       'Mahindra Scorpio SLX 2.6 Turbo 8 Str', 'Maruti Baleno Zeta 1.2',
       'BMW X3 2.5si', 'Hyundai EON 1.0 Kappa Magna Plus',
       'Chevrolet Enjoy 1.3 TCDi LTZ 7', 'Hyundai Verna 1.6 CRDi EX AT',
       'Honda BRV i-VTEC V CVT', 'Hyundai i10 Magna 1.2',
       'Toyota Innova 2.5 G4 Diesel 8-seater', 'Hyundai Verna 1.4 CX',
       'Hyundai i20 Sportz AT 1.4', 'Hyundai Verna 1.6 EX VTVT',
       'Hyundai i20 Magna Optional 1.2',
       'Toyota Innova 2.5 VX (Diesel) 8 Seater',
       'Mahindra KUV 100 D75 K8 5Str', 'Honda City i VTEC CVT VX',
       'Maruti Alto K10 VXI', 'Maruti Wagon R VXI Minor',
       'Mahindra TUV 300 2015-2019 T8', 'Hyundai Santro LS zipPlus',
       'Tata New Safari DICOR 2.2 EX 4x2', 'Audi A6 2011-2015 2.0 TDI',
       'Nissan Sunny Diesel XV', 'Toyota Innova 2.5 G4 Diesel 7-seater',
       'Renault Duster 110PS Diesel RxL', 'Maruti Dzire VXI',
       'Jeep Compass 2.0 Limited Option 4X4', 'Ford Fiesta 1.4 SXi TDCi',
       'Skoda Superb L&K 2.0 TDI AT', 'Mahindra Xylo E8',
       'Hyundai EON 1.0 Era Plus', 'Hyundai Elantra 2.0 SX Option AT',
       'Toyota Innova 2.0 V', 'Mahindra Xylo H9',
       'Hyundai Verna VTVT 1.6 SX', 'Hyundai Verna 1.6 CRDI',
       'Nissan Sunny 2011-2014 Diesel XL',
       'Chevrolet Sail Hatchback LS ABS', 'Hyundai Santro Xing GL Plus',
       'Nissan Sunny 2011-2014 XL AT Special Edition',
       'Honda Brio 1.2 VX MT', 'Honda CR-V 2.4 4WD AT',
       'Mercedes-Benz New C-Class C 220 CDI Celebration Edition',
       'Ford Ecosport 1.0 Ecoboost Titanium', 'Mercedes-Benz GLE 250d',
       'Toyota Fortuner 4x4 MT TRD Sportivo',
       'Mercedes-Benz CLA 200 D Sport Edition',
       'Honda Jazz 1.2 V CVT i VTEC', 'Toyota Fortuner 4x2 AT',
       'Mercedes-Benz E-Class 2009-2013 E350 CDI Avantgarde',
       'Mahindra TUV 300 P4', 'Volkswagen Polo 1.5 TDI Highline',
       'Maruti Wagon R LXI BS IV', 'Toyota Innova Crysta 2.8 ZX AT',
       'Maruti Ritz VDi ABS', 'Honda Jazz 1.2 VX i VTEC',
       'BMW 5 Series 520d Sedan', 'Hyundai Creta 1.4 CRDi S Plus',
       'Hyundai Getz GLE', 'Hyundai Xcent 1.2 Kappa SX Option',
       'Maruti Swift 1.3 VXi', 'Volvo S60 D5 Kinetic',
       'Honda Mobilio V i DTEC', 'Renault Captur 1.5 Diesel RXL',
       'Hyundai EON Sportz', 'Maruti A-Star AT VXI',
       'Audi A3 35 TDI Attraction', 'BMW 5 Series 2013-2017 530d M Sport',
       'Chevrolet Enjoy TCDi LS 7 Seater',
       'Mahindra Scorpio S10 8 Seater', 'Hyundai i20 2015-2017 1.2 Magna',
       'Renault Pulse RxZ', 'Maruti Swift Dzire ZDI',
       'Hyundai EON Magna Plus', 'Nissan Micra XL', 'Maruti Swift VXI',
       'Skoda Rapid 1.6 TDI Ambition', 'Fiat Punto 1.4 Emotion',
       'Honda Jazz 1.5 S i DTEC', 'Volvo XC60 D4 SUMMUM',
       'Maruti Ciaz ZDi Plus SHVS', 'Hyundai i20 1.4 CRDi Asta',
       'Maruti Omni 5 Seater BSIV', 'Hyundai Verna CRDi SX ABS',
       'Maruti Baleno Sigma 1.2', 'BMW X3 xDrive20d Advantage Edition',
       'Skoda Superb Style 1.8 TSI AT', 'Renault Duster 85PS Diesel RxL',
       'Honda WRV i-DTEC VX', 'Mercedes-Benz E-Class E 220 d',
       'Mercedes-Benz S Class 2005 2013 S 350 CDI', 'Hyundai Accent GLX',
       'Maruti Swift VXI BSIV', 'Mahindra KUV 100 G80 K4 Plus 5Str',
       'Tata Indica Vista Terra 1.2 Safire BS IV',
       'Land Rover Discovery Sport TD4 S',
       'Volkswagen Vento 1.5 TDI Highline Plus',
       'Tata Indica Vista TDI LS', 'Ford Figo Diesel LXI',
       'Honda Jazz 1.2 V i VTEC', 'Hyundai Grand i10 1.2 CRDi Magna',
       'Skoda Rapid 1.5 TDI Ambition',
       'Ford Ecosport 1.5 Ti VCT AT Titanium',
       'Hyundai Creta 1.6 SX Automatic Diesel',
       'Volkswagen CrossPolo 1.2 TDI', 'Ford Ikon 1.4 ZXi',
       'Porsche Cayenne Diesel', 'Honda Amaze E i-Vtech',
       'Audi A3 35 TDI Premium Plus',
       'Hyundai Verna Transform SX VGT CRDi BS III',
       'Ford Ecosport 1.5 DV5 MT Trend', 'Honda Amaze SX i-VTEC',
       'Volkswagen Vento 1.5 TDI Highline Plus AT',
       'Maruti SX4 S Cross DDiS 200 Zeta', 'Maruti 800 DX',
       'Toyota Innova Crysta 2.8 GX AT 8S', 'Maruti Ertiga VXI Petrol',
       'Maruti A-Star Vxi',
       'Fiat Avventura Urban Cross 1.3 Multijet Emotion',
       'Ford Fiesta 1.4 Duratec EXI Limited Edition',
       'Hyundai Elantra CRDi SX AT', 'Honda Accord 2.4 Elegance A/T',
       'Maruti Wagon R VXI AMT', 'Hyundai i20 1.2 Era',
       'Tata Nano Cx BSIV', 'Ford Ecosport 1.5 Ti VCT MT Trend',
       'Skoda Octavia Classic 1.9 TDI MT', 'Hyundai i20 Magna 1.2',
       'Maruti SX4 Vxi BSIV', 'Maruti Ritz LXi',
       'Maruti Alto K10 LXI CNG Optional',
       'Hyundai i20 2015-2017 Sportz AT 1.4',
       'Toyota Innova Crysta 2.4 G MT 8S', 'Mahindra Quanto C2',
       'Skoda Octavia 2.0 TDI MT Style', 'Hyundai Grand i10 AT Asta',
       'Hyundai i20 Magna 1.4 CRDi', 'Volvo S80 D5',
       'Renault Duster 85PS Diesel RxZ', 'Maruti Swift VXI BSIII',
       'Hyundai Creta 1.6 SX Plus Diesel',
       'Tata Tiago 1.2 Revotron XT Option', 'Audi A6 35 TDI Matrix',
       'Jaguar XF 2.0 Petrol Portfolio', 'Tata Manza Aqua Safire',
       'Tata Nano XTA', 'Maruti Wagon R AMT VXI',
       'Honda Civic 2010-2013 1.8 V AT', 'BMW 7 Series 2007-2012 730Ld',
       'Mahindra XUV500 AT W10 FWD', 'Hyundai Elantra SX AT',
       'Honda City i-DTEC SV', 'Volkswagen Polo Petrol Comfortline 1.2L',
       'Nissan 370Z AT', 'BMW 6 Series Gran Coupe',
       'Hyundai i20 1.4 Sportz', 'Hyundai Sonata Embera 2.0L CRDi MT',
       'Audi A6 2011-2015 35 TDI Technology',
       'Ford Classic 1.4 Duratorq CLXI', 'Renault Koleos 4X2 MT',
       'Land Rover Freelander 2 TD4 SE', 'Honda Amaze E i-DTEC',
       'Volvo V40 Cross Country D3', 'Ford Figo 1.2P Titanium MT',
       'Maruti Ciaz VDi Option SHVS',
       'Tata Indica Vista Terra Quadrajet 1.3L BS IV',
       'Hyundai EON Magna', 'Mahindra KUV 100 mFALCON G80 K6 Plus',
       'Hyundai i20 1.2 Spotz', 'Mercedes-Benz GLA Class 220 d 4MATIC',
       'Maruti Wagon R Stingray LXI', 'Mahindra Bolero Power Plus ZLX',
       'Tata Indica Vista Aura 1.3 Quadrajet',
       'Hyundai Elite i20 Petrol Sportz', 'Toyota Qualis FS B3',

In [65]:
df["Name"].dtypes

dtype('O')

## Location

In [66]:
df["Location"].isna().sum()

np.int64(0)

In [67]:
df["Location"].unique()

array(['Delhi', 'Coimbatore', 'Mumbai', 'Hyderabad', 'Pune', 'Jaipur',
       'Chennai', 'Kochi', 'Bangalore', 'Kolkata', 'Ahmedabad'],
      dtype=object)

In [68]:
df["Location"].value_counts()

Location
Mumbai        159
Pune          143
Coimbatore    136
Hyderabad     134
Kochi         121
Kolkata       119
Delhi         106
Chennai        97
Jaipur         86
Bangalore      82
Ahmedabad      51
Name: count, dtype: int64

## Year

In [69]:
df["Year"].isna().sum()

np.int64(0)

In [70]:
df["Year"].unique()

array([2014, 2013, 2017, 2012, 2016, 2015, 2011, 2007, 2008, 2009, 2019,
       2010, 2005, 2006, 2018, 2003, 1996, 2004, 2002, 2000])

In [71]:
df["Year"].value_counts()

Year
2015    185
2016    145
2013    142
2014    128
2017    122
2011    113
2012    110
2010     65
2018     63
2009     54
2008     33
2007     23
2019     17
2006     11
2005     11
2004      4
2003      3
2002      3
1996      1
2000      1
Name: count, dtype: int64

In [72]:
df["Year"].dtypes

dtype('int64')

## Kilometers_Driven

In [73]:
df["Kilometers_Driven"].isna().sum()

np.int64(0)

In [74]:
df["Kilometers_Driven"].unique()

array([ 40929,  54493,  34000, 139000,  29000,  85609,  59000,  65000,
        66000,  54684,  78000,  21000,  90000,  87628,  45000,  30788,
        39524, 140000,  15409,  36502, 200000,  70000,  36701,  72000,
        40000,  47000,  93500,  52000,  55429, 133000,  68000,  71000,
       121000, 107000,  51000,  13500,  13000,  81000,  66889,  32000,
        87001,  55000,   4000,  27778,   5000,  59299,  75000,   3413,
        62000, 105001,  89000,  50000,  70687, 104350, 150000,  35223,
        48000,  60000,   7000,  47572,  72727,   4708,  44198,  35000,
        63831,  17540,  14000,  75422,  67000,  79999,   5044,  31601,
        16000,  31700,  76969,  37000,  23000,  59098, 142299,  75731,
        69627,  49000,  25700,  80800, 110896,  62261,  27610,  89219,
         6700,  51599,  37489,  98000,  25183,  52100,  95000,  66346,
        69150,  31000,  63058,  22000,  73026,  21762,  29738,  16053,
        61665,  34820,  12000,  32287, 121134,  74485,  63000,  53190,
        26900,  40587,  27000,  29108,  18000,  10500,  61000,  24001,
        76000,  56000,  30000,  44263,  97899, 157301, 135000, 106000,
       121590,  64692,  41000,  25143, 109000,  69062,  34386,  20185,
        41585,  24000,  67630,  24192,  32248,  28000,  36471,  69689,
        69095,  46000, 119258,  38339,  59503,  93600,  58865,  64631,
       124298,  40001,  62659,  68138,  64141,   1000,  42000,  76677,
        66848, 111166,  94049,  20047,   1001,  89312,  93000,  64917,
        19678,  41309,  25038,  68673,  26343,  81245,  62100, 104000,
       114831,  80000,   9201,  55311,  58217,  70655, 125000,  82242,
       107281, 196000,  11791,  46950,  95942,  42925,  33750,  67365,
        67791,  20000,  90198,  77000,  42520,  87829,  21701,  86033,
        25000,  22987,  48725,  42500,  10000,  15669,  55331,  44535,
        74000,  77901,  58186,  14730,  88107,  53226,  73000,  77200,
       145278,  62083,  61696,  50142,  97513,  82000,  71501,  66095,
        49500,  25384,  27529,  69297,  36933, 194000,  42200,  53093,
        88000,  42954,  41700,  34464,  15000, 119256,  50036,  58000,
        53313,  83989,  86247,  33000, 100000,  65896, 120000,  26000,
        62300,  77801,  30134,  79038,  84419,  70200, 131503,  54652,
        92000,  44287, 205000,  31200,  85000, 126000,  58811,  52196,
        45105,  25160,  67700,  61062, 105000, 155550,  93884,  57200,
        93568,  54000,  40571,  17273, 100077,  39934,  30842, 150152,
        67038,  43985,  58598,  84500,  18006,  99000,  51200, 130000,
        32352,  12500,  53138, 170000,  38583,  22865,  62889, 153000,
        39000, 164000,  57178,  89564,  66727,  31056,  34782,  31736,
        38503,  45353,  69470,  63288,  25087, 134000,  54955,  45250,
        89190,  48184,  42125,  47052,  43189, 174889,  72135,  17660,
        29629,  69564,  34848,  27912,  62909,  33140,  25571,  12020,
        36665,  41502, 103000,  56239,  19964,  72246,  22764,  32090,
        83000, 141844,  32469,  56318,  26002,  56474,  64132,  41810,
        22177,  43518,  39100,  96000,  15322,  76041, 160000,  17000,
        54278,  30342,   9000,  46279, 113000,  67310,   1015,  83035,
        36983,  14148,  71428,  58997,  39842,  47490,  56600,  55409,
        59491,  18725,  61450,  18592,  65137,  14052,  45086,  25400,
       194500,  76551,   9700,  72017,  54407, 147000,  18856,  17700,
        82267,  27041,  28466,  35373,  82831,  39736,  26500,   5752,
        54841,  58469, 110000,  21127, 101000,  13664,  65371,  70428,
        69010,  55945,  10660,  52052,  62940, 102000,  37354,  66508,
        41372,  51637,  48233,  44550,  60001,  62766,  73575,  27270,
        41737,  28358,  75500,   9900,  68178,  52008,  48222,  76115,
        36009, 142000,  34224,  22230,  88700,  84004,  85009,  86000,
        93442,  31513,  75724,  69000,  56049,  96987,  33500,  64000,
        48045,  94000, 115000,  98472,  37800,  63617,  11282,  78984,
        43814,  65438,  28215,  15053,  38000,  64213, 158000,  71601,
        82328, 116000,   5600,  29300,  23342,  41078, 132000,  39408,
        27525,  82799,   8000,  47924,  33601,  80020,  87500,  59500,
        43000,  41850,  52300,  31924,  77914,  94385,  57000,  27039,
        11000,  57669, 124000,  29500,  54186,  36990,  23582,  87000,
        58634,  41377,  77372,  76681, 106565,  37492,  72843,  55653,
        44000,  43200, 117000,  63961,  63193,  44547,  79000, 108000,
        21302, 173000,  50299, 112999, 183000,  58840,  54982,  16292,
        11206,  32100,  22296,  36113,  39822,  81814,  10452,   1520,
        35315,  91722,  35976,  54486,  18366,  31176,  88375,  34500,
        25132,  48913,  35844,  14850,  42670,  33128,   7300,  53416,
        72002,  47634,  92448,  26189,  26300,  42285,  56967,  29566,
        41836,  19764,   8321, 174000, 119613,  55600,  38428,  24779,
        17431,  29347,  60249,   3013,  83503,  36000,  12899,  56839,
        46972,  96012,  59311,  32835,  60739,  19476,  53000,  65461,
        29215, 290000,  14519, 350000,  40130,  15500,  34948,  98245,
        36390, 122000,  79003,  78830,  18090,  70332,  63402,  65505,
       154000,  85142,  77800,  39549, 100922, 145000,  64139,  11574,
        14311,  18338,  17964,  55500,  49830,  53967,  83388, 113565,
       131000,  72253,  46346,  56371,  98500,  71588,  66800,  87248,
         9052,  67320,  28635,  78904,  16409,  61180,  59577,  24104,
        51843,  75383,  31861,  57900,  33544, 103189,  35007,  25678,
        65636,  21730,  46112,  60188, 115439, 104500,  26186,  58061,
       118000,  44379,  61041,  57297,  28700,  85264,  11934,  14927,
       111000,  63528,  41200,  39052,  55100,  76958,  70419,  63698,
        62715,  37922,  19000,  23389,  62269,  58898,  29110,  34649,
        25043,  36611,  45158,  36968,  53556,  78500,  33186,  61903,
        64168,   8044,  78835,  30631,  72573,  50215,   9999,   8300,
        83500, 134487,  23742,  60268,  70746,  78265,  76560,  29562,
        22003,   2890,   6512,  39008, 136441,  36200,  32506,  59800,
        63008,  57804,  37212,  61259, 183513,  78979,  30010,  27508,
        86107,  32746,  42758,  90904,  52612,  80724,  72734,  65475,
        72329,  49398,  44147,  22574,  26642,  81304,  36317, 137711,
        18980,  31293,  35161,  53590,  71467,  66287, 147202,  72566,
       190000,  25348,  58067,  43020,  27641,  46372,  27535,  55615,
        60595,  14301,  42741,   3800,  44702,  14300,  31542,  31717,
        99120,  41413,  67500,  30315,  39015,   6000,  21143,  42203,
        21380,  23955,  38568,  44556,  45463,  44776,  18242,  21190,
        89411,  52262,  72443])

In [75]:
df["Kilometers_Driven"].dtypes

dtype('int64')

## Fuel_Type

In [76]:
df["Fuel_Type"].isna().sum()

np.int64(0)

In [77]:
df["Fuel_Type"].unique()

array(['CNG', 'Petrol', 'Diesel', 'LPG'], dtype=object)

In [78]:
df["Fuel_Type"].value_counts()

Fuel_Type
Diesel    647
Petrol    579
CNG         6
LPG         2
Name: count, dtype: int64

## Transmission

In [79]:
df["Transmission"].isna().sum()

np.int64(0)

In [80]:
df["Transmission"].unique()

array(['Manual', 'Automatic'], dtype=object)

In [81]:
df["Transmission"].value_counts()

Transmission
Manual       905
Automatic    329
Name: count, dtype: int64

## Owner_Type

In [82]:
df["Owner_Type"].isna().sum()

np.int64(0)

In [83]:
df["Owner_Type"].unique()

array(['First', 'Second', 'Third', 'Fourth & Above'], dtype=object)

In [84]:
df["Owner_Type"].value_counts()

Owner_Type
First             1023
Second             184
Third               24
Fourth & Above       3
Name: count, dtype: int64

## Mileage

In [85]:
df["Mileage"].isna().sum()

np.int64(0)

In [86]:
df["Mileage"].unique()

array(['32.26 km/kg', '24.7 kmpl', '13.68 kmpl', '23.59 kmpl',
       '18.5 kmpl', '16.0 kmpl', '12.55 kmpl', '21.1 kmpl', '17.0 kmpl',
       '15.1 kmpl', '12.8 kmpl', '18.9 kmpl', '13.4 kmpl', '17.8 kmpl',
       '13.24 kmpl', '17.05 kmpl', '19.59 kmpl', '13.8 kmpl', '22.0 kmpl',
       '17.5 kmpl', '23.2 kmpl', '18.06 kmpl', '15.5 kmpl', '19.7 kmpl',
       '27.3 kmpl', '21.66 kmpl', '15.11 kmpl', '19.81 kmpl', '10.5 kmpl',
       '23.4 kmpl', '19.1 kmpl', '14.84 kmpl', '15.29 kmpl', '22.48 kmpl',
       '27.39 kmpl', '17.11 kmpl', '16.55 kmpl', '15.41 kmpl',
       '24.52 kmpl', '20.73 kmpl', '20.0 kmpl', '12.99 kmpl',
       '18.88 kmpl', '22.7 kmpl', '11.4 kmpl', '14.16 kmpl', '17.01 kmpl',
       '24.3 kmpl', '19.09 kmpl', '17.7 kmpl', '14.53 kmpl', '18.6 kmpl',
       '20.14 kmpl', '23.0 kmpl', '18.2 kmpl', '15.4 kmpl', '18.4 kmpl',
       '16.02 kmpl', '0.0 kmpl', '18.16 kmpl', '23.84 kmpl', '23.08 kmpl',
       '18.12 kmpl', '19.16 kmpl', '21.43 kmpl', '22.32 kmpl',
       '21.21 kmpl', '11.07 kmpl', '13.07 kmpl', '15.3 kmpl', '11.9 kmpl',
       '17.92 kmpl', '21.4 kmpl', '10.2 kmpl', '19.34 kmpl', '19.0 kmpl',
       '26.0 kmpl', '25.8 kmpl', '22.07 kmpl', '22.3 kmpl', '17.32 kmpl',
       '19.4 kmpl', '19.71 kmpl', '16.47 kmpl', '19.2 kmpl', '16.73 kmpl',
       '19.3 kmpl', '21.9 kmpl', '26.59 kmpl', '16.09 kmpl', '25.44 kmpl',
       '18.51 kmpl', '12.0 kmpl', '19.83 kmpl', '20.89 kmpl', '13.9 kmpl',
       '22.74 kmpl', '13.6 kmpl', '18.15 kmpl', '20.54 kmpl', '14.4 kmpl',
       '13.5 kmpl', '18.0 kmpl', '22.5 kmpl', '20.36 kmpl', '13.1 kmpl',
       '16.36 kmpl', '24.0 kmpl', '15.0 kmpl', '23.1 kmpl', '13.0 kmpl',
       '14.8 kmpl', '17.3 kmpl', '11.3 kmpl', '10.13 kmpl', '20.64 kmpl',
       '16.78 kmpl', '14.3 kmpl', '21.64 kmpl', '15.26 kmpl',
       '15.04 kmpl', '24.2 kmpl', '16.9 kmpl', '11.8 kmpl', '18.1 kmpl',
       '23.9 kmpl', '16.77 kmpl', '14.1 kmpl', '19.01 kmpl', '28.4 kmpl',
       '14.74 kmpl', '21.76 kmpl', '19.27 kmpl', '16.8 kmpl',
       '17.68 kmpl', '14.6 kmpl', '17.19 kmpl', '24.5 kmpl', '21.02 kmpl',
       '12.2 kmpl', '15.17 kmpl', '16.2 kmpl', '16.3 kmpl', '17.71 kmpl',
       '15.6 kmpl', '19.67 kmpl', '17.3 km/kg', '17.1 kmpl', '13.49 kmpl',
       '20.92 kmpl', '20.46 kmpl', '14.2 kmpl', '25.2 kmpl', '14.21 kmpl',
       '13.2 kmpl', '15.2 kmpl', '11.68 kmpl', '21.19 kmpl', '13.7 kmpl',
       '21.14 kmpl', '12.3 kmpl', '16.1 kmpl', '22.9 kmpl', '11.5 kmpl',
       '21.03 kmpl', '20.77 kmpl', '12.07 kmpl', '24.07 kmpl',
       '25.0 kmpl', '11.1 kmpl', '22.54 kmpl', '20.8 kmpl', '14.28 kmpl',
       '11.7 kmpl', '15.96 kmpl', '14.0 kmpl', '25.32 kmpl', '14.24 kmpl',
       '17.88 kmpl', '19.69 kmpl', '20.3 kmpl', '12.39 kmpl', '20.4 kmpl',
       '20.51 kmpl', '18.25 kmpl', '20.68 kmpl', '9.1 kmpl',
       '11.88 km/kg', '11.2 kmpl', '11.0 kmpl', '16.38 kmpl',
       '15.73 kmpl', '14.81 kmpl', '19.64 kmpl', '12.7 kmpl', '17.6 kmpl',
       '19.15 kmpl', '17.9 kmpl', '21.5 kmpl', '22.77 kmpl', '16.5 kmpl',
       '22.69 kmpl', '20.5 kmpl', '18.33 kmpl', '12.08 kmpl',
       '16.95 kmpl', '20.7 kmpl', '9.74 kmpl', '16.46 kmpl', '16.98 kmpl',
       '27.62 kmpl', '25.4 kmpl', '15.63 kmpl', '15.56 kmpl',
       '16.52 kmpl', '25.17 kmpl', '19.33 kmpl', '18.3 kmpl', '15.8 kmpl',
       '17.4 kmpl', '12.6 kmpl', '23.5 kmpl', '18.49 kmpl', '11.57 kmpl',
       '22.71 kmpl', '18.19 kmpl', '14.62 kmpl', '12.4 kmpl',
       '14.02 kmpl', '22.1 kmpl', '17.97 kmpl', '10.1 kmpl', '11.78 kmpl',
       '21.72 kmpl', '11.36 kmpl', '18.7 kmpl', '18.48 kmpl',
       '21.38 kmpl', '20.37 kmpl', '20.38 kmpl', '14.69 kmpl',
       '14.7 kmpl', '28.09 kmpl', '14.67 kmpl', '19.87 kmpl', '25.5 kmpl',
       '12.83 kmpl', '15.15 kmpl', '23.65 kmpl', '16.6 kmpl',
       '16.51 kmpl', '17.21 kmpl', '21.0 kmpl', '18.53 kmpl', '10.8 kmpl',
       '14.49 kmpl', '14.5 kmpl', '25.6 kmpl', '10.0 kmpl', '17.54 kmpl',
       '19.68 kmpl', '17.15 kmpl', '23.3 kmpl', '20.85 kmpl',
       '20.34 kmpl', '19.5 kmpl', '12.62 kmpl', '12.05 kmpl',
       '26.21 kmpl', '24.4 kmpl', '15.85 kmpl', '19.6 kmpl', '14.95 kmpl',
       '8.7 kmpl', '13.2 km/kg', '15.1 km/kg', '14.94 kmpl', '12.37 kmpl',
       '30.46 km/kg', '19.98 kmpl', '20.45 kmpl', '21.79 kmpl',
       '24.8 kmpl', '7.94 kmpl', '23.03 kmpl', '16.93 kmpl', '11.74 kmpl',
       '13.22 kmpl', '17.57 kmpl', '11.18 kmpl', '22.95 kmpl',
       '17.2 kmpl', '12.98 kmpl', '12.19 kmpl', '15.9 kmpl', '14.9 kmpl',
       '8.45 kmpl', '23.8 kmpl', '9.0 kmpl', '15.97 kmpl', '27.28 kmpl'],
      dtype=object)

In [87]:
df["Mileage"].value_counts()

Mileage
17.0 kmpl     35
18.9 kmpl     29
18.6 kmpl     25
21.1 kmpl     20
18.0 kmpl     20
              ..
23.5 kmpl      1
17.19 kmpl     1
21.02 kmpl     1
19.33 kmpl     1
27.28 kmpl     1
Name: count, Length: 301, dtype: int64

In [88]:
df["Mileage"] = df["Mileage"].str.extract(r"(\d+\.?\d*)")[0].astype(float)
df["Mileage_kmpl"] = df["Mileage"] * 1.33

In [89]:
df["Mileage_kmpl"].isna().sum()

np.int64(0)

In [90]:
df["Mileage_kmpl"]=df["Mileage_kmpl"].astype(int)

In [91]:
df["Mileage_kmpl"].dtypes

dtype('int64')

In [92]:
df["Mileage_kmpl"].value_counts()

Mileage_kmpl
25    100
22     98
23     94
24     88
17     86
27     74
26     69
21     62
30     57
28     55
20     54
29     52
19     51
18     41
32     39
15     36
31     32
16     26
33     24
34     21
13     13
0      13
14     11
36      9
37      9
35      8
12      4
11      3
42      3
40      1
10      1
Name: count, dtype: int64

In [94]:
df.drop("Mileage", axis=1, inplace=True)

In [95]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine,Power,Seats,Mileage_kmpl
0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,998 CC,58.2 bhp,4.0,42
1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,796 CC,47.3 bhp,5.0,32
2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,2393 CC,147.8 bhp,7.0,18
3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,1364 CC,null bhp,5.0,31
4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,1197 CC,82.85 bhp,5.0,24
...,...,...,...,...,...,...,...,...,...,...,...
1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,1598 CC,103.6 bhp,5.0,27
1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,1197 CC,103.6 bhp,5.0,22
1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,1461 CC,63.1 bhp,5.0,30
1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,1197 CC,103.6 bhp,5.0,22
1233,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,2148 CC,170 bhp,5.0,13

## Engine

In [96]:
df["Engine"].isna().sum()

np.int64(10)

In [97]:
df.dropna(subset="Engine", inplace=True)

In [98]:
df["Engine"].isna().sum()

np.int64(0)

In [99]:
df["Engine"].unique()

array(['998 CC', '796 CC', '2393 CC', '1364 CC', '1197 CC', '2179 CC',
       '2982 CC', '814 CC', '1497 CC', '1968 CC', '1794 CC', '1248 CC',
       '1598 CC', '1995 CC', '1399 CC', '1298 CC', '1198 CC', '1799 CC',
       '1299 CC', '1498 CC', '1086 CC', '2835 CC', '1591 CC', '2494 CC',
       '1373 CC', '2143 CC', '2953 CC', '1396 CC', '1798 CC', '1199 CC',
       '1196 CC', '1461 CC', '2487 CC', '1582 CC', '2496 CC', '1368 CC',
       '1596 CC', '1595 CC', '2354 CC', '624 CC', '2993 CC', '936 CC',
       '2987 CC', '1999 CC', '999 CC', '2000 CC', '1493 CC', '1120 CC',
       '3498 CC', '1496 CC', '1405 CC', '1896 CC', '2967 CC', '2477 CC',
       '1948 CC', '1172 CC', '1797 CC', '2498 CC', '1061 CC', '1150 CC',
       '1495 CC', '2499 CC', '1796 CC', '2362 CC', '2523 CC', '5998 CC',
       '2755 CC', '2400 CC', '2349 CC', '995 CC', '1998 CC', '2999 CC',
       '1795 CC', '1984 CC', '793 CC', '1341 CC', '1186 CC', '1499 CC',
       '1991 CC', '799 CC', '1586 CC', '2497 CC', '1956 CC', '1950 CC',
       '1462 CC', '1388 CC', '1997 CC', '3696 CC', '2446 CC', '2198 CC',
       '2489 CC', '2147 CC', '2359 CC', '2996 CC', '2495 CC', '2148 CC',
       '4395 CC', '1389 CC', '1193 CC', '2696 CC', '2979 CC', '1590 CC',
       '1599 CC', '1047 CC'], dtype=object)

In [100]:
df["Engine"] = df["Engine"].str.replace(" CC", "", regex=False).astype(int)

In [101]:
df["Engine"].value_counts()

Engine
1197    126
1248     98
1498     66
1198     54
998      50
       ...
1948      1
1299      1
5998      1
2362      1
1047      1
Name: count, Length: 104, dtype: int64

In [102]:
df["Engine"].dtypes

dtype('int64')

In [103]:
df.rename(columns={"Engine": "Engine_CC"}, inplace=True)

In [104]:
df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Engine_CC', 'Power', 'Seats',
       'Mileage_kmpl'],
      dtype='object')

## Power

In [105]:
df["Power"].isna().sum()

np.int64(0)

In [107]:
df["Power"].unique()

array(['58.2 bhp', '47.3 bhp', '147.8 bhp', 'null bhp', '82.85 bhp',
       '140 bhp', '168.7 bhp', '55.2 bhp', '118 bhp', '167.6 bhp',
       '82 bhp', '125 bhp', '75 bhp', '102.5 bhp', '184 bhp', '68 bhp',
       '81.80 bhp', '85.8 bhp', '73.94 bhp', '132 bhp', '70 bhp',
       '46.3 bhp', '98.6 bhp', '103.52 bhp', '80 bhp', '67.06 bhp',
       '103.6 bhp', '68.05 bhp', '107.2 bhp', '74 bhp', '121.3 bhp',
       '102 bhp', '190 bhp', '174.33 bhp', '88.5 bhp', '91.1 bhp',
       '136 bhp', '100.6 bhp', '89.84 bhp', '153.86 bhp', '174.3 bhp',
       '67.04 bhp', '69 bhp', '78 bhp', '138.1 bhp', '81.83 bhp',
       '88.8 bhp', '67 bhp', '82.5 bhp', '120 bhp', '108.62 bhp',
       '67.1 bhp', '86.8 bhp', '93.7 bhp', '62 bhp', '84 bhp', '79.4 bhp',
       '63.1 bhp', '100 bhp', '81.86 bhp', '175.67 bhp', '87.2 bhp',
       '126.32 bhp', '103.2 bhp', '179.5 bhp', '88.76 bhp', '99.6 bhp',
       '120.7 bhp', '62.1 bhp', '83.1 bhp', '180 bhp', '75.94 bhp',
       '126.24 bhp', '35 bhp', '73.9 bhp', '138.13 bhp', '201.15 bhp',
       '218 bhp', '57.6 bhp', '147.51 bhp', '224 bhp', '66.1 bhp',
       '130.3 bhp', '177 bhp', '90 bhp', '123.24 bhp', '130 bhp',
       '148 bhp', '78.9 bhp', '108.495 bhp', '187.7 bhp', '204 bhp',
       '165 bhp', '98.96 bhp', '117.3 bhp', '254.8 bhp', '364.9 bhp',
       '108.5 bhp', '201.1 bhp', '88.73 bhp', '71 bhp', '160 bhp',
       '105 bhp', '84.8 bhp', '203.2 bhp', '246.7 bhp', '110 bhp',
       '37.48 bhp', '261.49 bhp', '108.45 bhp', '73.75 bhp', '270.9 bhp',
       '56.3 bhp', '167.62 bhp', '34.2 bhp', '88.7 bhp', '175.56 bhp',
       '126.2 bhp', '181 bhp', '147.5 bhp', '78.8 bhp', '70.02 bhp',
       '57.5 bhp', '121.4 bhp', '138.03 bhp', '83.8 bhp', '246.74 bhp',
       '74.9 bhp', '203 bhp', '94 bhp', '140.8 bhp', '112 bhp', '170 bhp',
       '157.75 bhp', '185 bhp', '37 bhp', '171 bhp', '164.7 bhp',
       '116.3 bhp', '65 bhp', '241.4 bhp', '76.8 bhp', '142 bhp',
       '64.1 bhp', '73 bhp', '177.6 bhp', '86.7 bhp', '77 bhp', '616 bhp',
       '174.5 bhp', '48.21 bhp', '144 bhp', '69.01 bhp', '91.7 bhp',
       '187.74 bhp', '178 bhp', '200 bhp', '241 bhp', '170.30 bhp',
       '182.46 bhp', '106 bhp', '163.7 bhp', '245.41 bhp', '98.59 bhp',
       '63 bhp', '167.7 bhp', '161 bhp', '97.7 bhp', '127 bhp',
       '168.5 bhp', '76 bhp', '113.98 bhp', '120.69 bhp', '208 bhp',
       '258 bhp', '47 bhp', '61 bhp', '73.97 bhp', '110.4 bhp', '252 bhp',
       '123.7 bhp', '53.3 bhp', '147.9 bhp', '85.80 bhp', '103.5 bhp',
       '103.3 bhp', '73.74 bhp', '126.3 bhp', '82.9 bhp', '149.92 bhp',
       '118.3 bhp', '76.9 bhp', '152 bhp', '116.4 bhp', '123.37 bhp',
       '169 bhp', '108.4 bhp', '210 bhp', '171.5 bhp', '83 bhp',
       '215 bhp', '143 bhp', '73.8 bhp', '63.12 bhp', '177.46 bhp',
       '191.34 bhp', '282 bhp', '108.49 bhp', '240 bhp', '103 bhp',
       '91.72 bhp', '66 bhp', '141 bhp', '88.2 bhp', '130.2 bhp',
       '147.4 bhp', '328.5 bhp', '313 bhp', '115 bhp', '150 bhp',
       '55 bhp', '83.14 bhp', '158 bhp', '98.63 bhp', '224.34 bhp',
       '134 bhp', '107.3 bhp', '53.64 bhp', '198.25 bhp', '362.07 bhp',
       '254.79 bhp', '104.68 bhp', '157.7 bhp', '450 bhp', '88 bhp',
       '186 bhp', '98.82 bhp', '360 bhp', '178.4 bhp', '236 bhp',
       '85 bhp', '192 bhp', '98.79 bhp', '112.2 bhp', '321 bhp',
       '241.6 bhp', '157.8 bhp', '121.36 bhp', '92.7 bhp'], dtype=object)

In [117]:
df["Power"] = (
    df["Power"]
    .astype(str)
    .str.extract(r"(\d+\.?\d*)")[0]
    .astype(float)
)

In [118]:
df["Power"].dtypes

dtype('float64')

In [119]:
df["Power"].unique()

array([ 58.,  47., 148.,  nan,  83., 140., 169.,  55., 118., 168.,  82.,
       125.,  75., 102., 184.,  68.,  86.,  74., 132.,  70.,  46.,  99.,
       104.,  80.,  67., 107., 121., 190., 174.,  88.,  91., 136., 101.,
        90., 154.,  69.,  78., 138.,  89., 120., 109.,  87.,  94.,  62.,
        84.,  79.,  63., 100., 176., 126., 103., 180.,  76.,  35., 201.,
       218., 224.,  66., 130., 177., 123., 108., 188., 204., 165., 117.,
       255., 365.,  71., 160., 105.,  85., 203., 247., 110.,  37., 261.,
       271.,  56.,  34., 181., 141., 112., 170., 158., 185., 171., 116.,
        65., 241.,  77., 142.,  64.,  73., 178., 616.,  48., 144.,  92.,
       200., 182., 106., 164., 245., 161.,  98., 127., 114., 208., 258.,
        61., 252., 124.,  53., 150., 152., 210., 172., 215., 143., 191.,
       282., 240., 147., 328., 313., 115., 134.,  54., 198., 362., 450.,
       186., 360., 236., 192., 321., 242.,  93.])

In [123]:
df["Power"].isna().sum()

np.int64(22)

In [124]:
df.dropna(subset="Power", inplace=True)

In [125]:
df["Power"]=df["Power"].astype(int)

In [126]:
df["Power"].dtypes

dtype('int64')

## Seats

In [127]:
df["Seats"].isna().sum()

np.int64(1)

In [128]:
df.dropna(subset="Seats", inplace=True)

In [129]:
df["Seats"].unique()

array([ 4.,  5.,  7.,  6.,  8., 10.,  2.])

In [130]:
df["Seats"].value_counts()

Seats
5.0     1011
7.0      122
8.0       36
4.0       20
6.0        7
10.0       3
2.0        2
Name: count, dtype: int64

In [131]:
df["Seats"]=df["Seats"].astype(int)

In [132]:
df["Seats"].dtypes

dtype('int64')

In [133]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine_CC,Power,Seats,Mileage_kmpl
0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,998,58,4,42
1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,796,47,5,32
2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,2393,148,7,18
4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,1197,83,5,24
5,Mahindra XUV500 W8 2WD,Coimbatore,2016,85609,Diesel,Manual,Second,2179,140,7,21
...,...,...,...,...,...,...,...,...,...,...,...
1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,1598,104,5,27
1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,1197,104,5,22
1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,1461,63,5,30
1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,1197,104,5,22
1233,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,2148,170,5,13

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1233
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               1201 non-null   object
 1   Location           1201 non-null   object
 2   Year               1201 non-null   int64
 3   Kilometers_Driven  1201 non-null   int64
 4   Fuel_Type          1201 non-null   object
 5   Transmission       1201 non-null   object
 6   Owner_Type         1201 non-null   object
 7   Engine_CC          1201 non-null   int64
 8   Power              1201 non-null   int64
 9   Seats              1201 non-null   int64
 10  Mileage_kmpl       1201 non-null   int64
dtypes: int64(6), object(5)
memory usage: 112.6+ KB

In [136]:
df.to_csv("Cars24_Used_car_data.csv", index=False)