In [1]:
# 1. Load the CSV using Pandas and display the first 10 rows.

import pandas as pd

df = pd.read_csv("C:\\Users\\bhoom\\Downloads\\customer_data - customer_data.csv")
df.head()

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???

In [2]:
# 2. Check the number of rows and columns in the dataset.
df.shape

(2000, 15)

In [3]:
# 3. Display all column names and identify which column names contain
# leading/trailing spaces or inconsistent capitalization.

for i in df.columns:
    print(i)

Customer ID
Age
income_usd
credit Score
tenure_years
monthly_visits
satisfaction
City
customer_segment
gender
is_active
churn_flag
signup_date
lead_source
notes_text

In [4]:
for i in df.columns:
    if i != i.title():
        df = df.rename(columns = {i:i.title()})

In [5]:
for i in df.columns:
    print(i)

Customer Id
Age
Income_Usd
Credit Score
Tenure_Years
Monthly_Visits
Satisfaction
City
Customer_Segment
Gender
Is_Active
Churn_Flag
Signup_Date
Lead_Source
Notes_Text

In [6]:
# 4. Check the data type of every column using Pandas.

df.dtypes

Customer Id          object
Age                  object
Income_Usd           object
Credit Score         object
Tenure_Years        float64
Monthly_Visits      float64
Satisfaction        float64
City                 object
Customer_Segment     object
Gender               object
Is_Active            object
Churn_Flag           object
Signup_Date          object
Lead_Source          object
Notes_Text           object
dtype: object

In [7]:
# 5. Calculate the number and percentage of missing values in every column.

for i in df.columns:
    print(df[i].isna().sum()/20)

1.0
16.55
22.0
18.0
12.9
14.0
19.95
15.0
19.0
12.0
17.0
8.0
12.0
21.0
32.8

In [8]:
# 6. Find the rows where Customer ID is missing.

df[df["Customer Id"].isna()]

,Customer Id,Age,Income_Usd,Credit Score,Tenure_Years,Monthly_Visits,Satisfaction,City,Customer_Segment,Gender,Is_Active,Churn_Flag,Signup_Date,Lead_Source,Notes_Text
162,NaN,18,61780.99213,715.4452325,10.137001,5.0,3.179153,Delhi,UNKNOWN,Female,NaN,No,2021-04-22,website,follow-up needed
226,NaN,18,58188.80528,737.9284458,15.655950,12.0,3.330254,Chennai,Consumer,Female,Y,NaN,2022-03-18,Referral,normal
300,NaN,NaN,93665.74378,703.9692987,12.723292,7.0,NaN,Pune,SMB,Female,1,No,NaN,Email,follow-up needed
421,NaN,29.6 years,NaN,641.3441152,8.940646,5.0,3.687539,NaN,Consumer,Female,1,No,2021-12-05,Unknown,NaN
770,NaN,20.39545706,92366.06753,767.8048841,4.524943,3.0,4.358065,Mumbai,Enterprise,f,N,No,2021-09-05,???,NaN
821,NaN,46.41996378,81119.71831,597.3307848,1.076200,5.0,4.346306,Delhi,consumer,f,1,Yes,2022-12-26,Email,NaN
876,NaN,36.57634009,76629.87047,699.109735,4.977078,6.0,2.700057,Mumbai,consumer,M,N,Yes,2021-07-01,referral,good
993,NaN,47.54933612,NaN,NaN,0.693710,4.0,3.659781,NaN,Enterprise,NaN,NaN,No,2024-07-09,Referral,late payment
1023,NaN,NaN,34219.41505,NaN,3.779121,4.0,3.529211,Hyderabad,NaN,M,N,No,2023-07-05,Google Ads,ok
1188,NaN,28.97406958,NaN,744 pts,7.947965,8.0,2.379383,Hyderabad,Consumer,f,Yes,No,2026-06-06,NaN,urgent
1202,NaN,42.23152645,35310.77625,684.8618643,2.465432,6.0,4.979391,Delhi,SMB,m,1,No,2024-10-10,google_ads,late payment
1212,NaN,56.44358785,"$99,697",749.3298384,3.743193,6.0,NaN,NaN,NaN,M,Y,Yes,2024-07-18,WEB,NaN
1248,NaN,34.60645101,96811.19575,798.1150352,1.551247,5.0,3.288656,Mumbai,SMB.,M,N,No,2023-09-16,Social,follow-up needed
1338,NaN,26.5 years,"$89,682",692.0794813,1.877392,4.0,3.783551,Pune,Consumer,m,N,No,2023-12-04,WEB,NaN
1346,NaN,46.22898842,60122.78196,684.8548451,3.837557,2.0,4.267750,Mumbai,consumer,F,N,Yes,2023-01-01,referral,follow-up needed
1448,NaN,18,NaN,628.337014,7.137356,5.0,NaN,Pune,Enterprise,Female,no,NaN,2024-08-25,Google Ads,NaN
1451,NaN,47.20187446,28270.08329,549.3662455,3.019237,6.0,3.441021,Hyderabad,SMB,m,yes,Yes,2023-10-12,Unknown,good
1462,NaN,49.99203599,58348.28529,511.5806801,2.775352,NaN,NaN,Mumbai,SMB,Female,no,No,2024-07-07,NaN,NaN
1564,NaN,42.96550781,"$64,045",561 pts,4.549291,4.0,3.513904,Chennai,Consumer,m,No,No,03/08/2023,Email,NaN
1652,NaN,33.27510593,37475.10034,NaN,4.345689,11.0,-999.000000,Mumbai,SMB,f,NaN,NaN,2022-02-15,Social,ok

In [9]:
# 7. Remove leading/trailing whitespace from all column names and convert them to lowercase with underscores.

for i in df.columns:
    if i != i.lower():
        df = df.rename(columns = {i:i.lower()})

In [10]:
df

,customer id,age,income_usd,credit score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

In [11]:
df.columns = df.columns.str.replace(' ','_')
for i in df.columns:
    print(i)

customer_id
age
income_usd
credit_score
tenure_years
monthly_visits
satisfaction
city
customer_segment
gender
is_active
churn_flag
signup_date
lead_source
notes_text

In [12]:
# 8. Identify duplicate Customer ID values and count how many duplicates exist.

df['customer_id'].duplicated().sum()
df[df['customer_id'].duplicated()]

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
226,NaN,18,58188.80528,737.9284458,15.655950,12.0,3.330254,Chennai,Consumer,Female,Y,NaN,2022-03-18,Referral,normal
300,NaN,NaN,93665.74378,703.9692987,12.723292,7.0,NaN,Pune,SMB,Female,1,No,NaN,Email,follow-up needed
421,NaN,29.6 years,NaN,641.3441152,8.940646,5.0,3.687539,NaN,Consumer,Female,1,No,2021-12-05,Unknown,NaN
770,NaN,20.39545706,92366.06753,767.8048841,4.524943,3.0,4.358065,Mumbai,Enterprise,f,N,No,2021-09-05,???,NaN
821,NaN,46.41996378,81119.71831,597.3307848,1.076200,5.0,4.346306,Delhi,consumer,f,1,Yes,2022-12-26,Email,NaN
876,NaN,36.57634009,76629.87047,699.109735,4.977078,6.0,2.700057,Mumbai,consumer,M,N,Yes,2021-07-01,referral,good
993,NaN,47.54933612,NaN,NaN,0.693710,4.0,3.659781,NaN,Enterprise,NaN,NaN,No,2024-07-09,Referral,late payment
1023,NaN,NaN,34219.41505,NaN,3.779121,4.0,3.529211,Hyderabad,NaN,M,N,No,2023-07-05,Google Ads,ok
1188,NaN,28.97406958,NaN,744 pts,7.947965,8.0,2.379383,Hyderabad,Consumer,f,Yes,No,2026-06-06,NaN,urgent
1202,NaN,42.23152645,35310.77625,684.8618643,2.465432,6.0,4.979391,Delhi,SMB,m,1,No,2024-10-10,google_ads,late payment
1212,NaN,56.44358785,"$99,697",749.3298384,3.743193,6.0,NaN,NaN,NaN,M,Y,Yes,2024-07-18,WEB,NaN
1248,NaN,34.60645101,96811.19575,798.1150352,1.551247,5.0,3.288656,Mumbai,SMB.,M,N,No,2023-09-16,Social,follow-up needed
1338,NaN,26.5 years,"$89,682",692.0794813,1.877392,4.0,3.783551,Pune,Consumer,m,N,No,2023-12-04,WEB,NaN
1346,NaN,46.22898842,60122.78196,684.8548451,3.837557,2.0,4.267750,Mumbai,consumer,F,N,Yes,2023-01-01,referral,follow-up needed
1448,NaN,18,NaN,628.337014,7.137356,5.0,NaN,Pune,Enterprise,Female,no,NaN,2024-08-25,Google Ads,NaN
1451,NaN,47.20187446,28270.08329,549.3662455,3.019237,6.0,3.441021,Hyderabad,SMB,m,yes,Yes,2023-10-12,Unknown,good
1462,NaN,49.99203599,58348.28529,511.5806801,2.775352,NaN,NaN,Mumbai,SMB,Female,no,No,2024-07-07,NaN,NaN
1564,NaN,42.96550781,"$64,045",561 pts,4.549291,4.0,3.513904,Chennai,Consumer,m,No,No,03/08/2023,Email,NaN
1652,NaN,33.27510593,37475.10034,NaN,4.345689,11.0,-999.000000,Mumbai,SMB,f,NaN,NaN,2022-02-15,Social,ok

In [13]:
df['customer_id'].duplicated().value_counts()

customer_id
False    1981
True       19
Name: count, dtype: int64

In [14]:
# 9. Remove duplicate customer records while keeping the first occurrence.
df = df.drop_duplicates()
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

In [15]:
# 10.Find all unique values in the customer_segment column and identify
# inconsistent categories such as Consumer, consumer, consumer , etc.

df['customer_segment'].value_counts()

customer_segment
Consumer      666
SMB           395
Enterprise    293
consumer      121
UNKNOWN        76
SMB.           69
Name: count, dtype: int64

In [16]:
df=df.replace({"customer_segment":{"Consumer":"consumer","SMB.":"SMB"}})

In [17]:
df['customer_segment'].value_counts()

customer_segment
consumer      787
SMB           464
Enterprise    293
UNKNOWN        76
Name: count, dtype: int64

In [18]:
# 11.Clean the customer_segment column by standardizing capitalization and whitespace.

df['customer_segment'] = df['customer_segment'].str.strip().str.title()
df['customer_segment'].value_counts()

customer_segment
Consumer      787
Smb           464
Enterprise    293
Unknown        76
Name: count, dtype: int64

In [19]:
# 12.Find all unique values in the gender column and convert them into consistent
# categories such as Male and Female.

df["gender"].value_counts()

gender
m         318
Male      300
F         294
f         289
Female    288
M         271
Name: count, dtype: int64

In [20]:
df=df.replace({"gender":{"m":"Male","M":"Male","f":"Female","F":"Female"}})
df['gender'].value_counts()

gender
Male      889
Female    871
Name: count, dtype: int64

In [21]:
# 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and
# No, no, N, 0 become 0.

df['is_active'].value_counts()

is_active
Yes    227
1      224
No     218
N      216
yes    201
Y      197
no     191
0      186
Name: count, dtype: int64

In [22]:
df=df.replace({"is_active":{"Yes":1,"1":1,"yes":1,"Y":1,
                           "No":0,"N":0,"no":0,"0":0}})
df['is_active'].value_counts()

C:\Users\bhoom\AppData\Local\Temp\ipykernel_9248\1602207922.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace({"is_active":{"Yes":1,"1":1,"yes":1,"Y":1,

is_active
1.0    849
0.0    811
Name: count, dtype: int64

In [23]:
# 14.Convert the churn_flag column from categorical values (Yes/No) into a binary
# numerical column (1/0).

df["churn_flag"].value_counts()

churn_flag
No     1394
Yes     446
Name: count, dtype: int64

In [24]:
df=df.replace({"churn_flag":{"No":0,"Yes":1}})
df['churn_flag'].value_counts()

C:\Users\bhoom\AppData\Local\Temp\ipykernel_9248\1638004588.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace({"churn_flag":{"No":0,"Yes":1}})

churn_flag
0.0    1394
1.0     446
Name: count, dtype: int64

In [25]:
# 15.Identify all values in income_usd that cannot be directly interpreted as numbers.

for i in df["income_usd"].dropna().unique():
    try:
        float(i)
    except:
        print(i)

$44,696
$41,941
$123,682
$40,978
$45,565
$112,864
$38,946
$93,738
$70,056
$26,771
missing
$48,959
$36,410
$86,520
$88,847
$88,960
$50,211
$104,630
$72,142
$34,864
$130,837
$90,730
$29,657
$60,407
₹55k
$506,709
$71,214
$191,997
$35,341
$171,139
$65,761
$30,152
$47,631
$319,924
$46,216
$49,366
$78,703
$44,955
$76,860
$50,094
$129,799
$32,702
$33,399
$19,760
$146,497
$30,746
$107,324
$19,808
error
$49,885
$22,575
$53,462
$100,254
$37,397
$89,920
$60,643
$153,576
$114,703
$117,570
$155,204
$39,065
$108,002
$33,428
$18,612
$32,495
$31,099
$60,008
$31,588
$84,034
$92,205
$30,921
$38,009
$61,792
$48,656
$49,855
$23,569
$38,605
$37,860
$47,580
$24,527
$78,202
$53,993
$64,415
not available
$99,869
$543,686
$74,109
$45,886
$75,683
$59,291
$41,955
$37,026
$13,148
$56,234
$73,642
$44,722
$39,362
$41,269
$33,259
$34,160
$45,415
$55,242
$99,697
$35,506
$352,568
$25,393
$20,322
$65,732
$15,187
$61,230
$38,916
$97,960
$93,193
$42,625
$36,305
$89,682
$33,715
$34,982
$45,435
$212,590
$151,415
$38,849
$256,510
$25,921
$52,112
$155,352
$45,288
$76,139
$48,047
$27,675
$55,161
$63,822
$124,103
$26,579
$27,606
$87,822
$83,857
$31,808
$24,295
$22,540
$38,251
$41,234
$506,702
$64,045
$52,352
$31,857
$98,449
$54,157
$49,817
$17,863
$160,831
$119,220
$264,787
$69,968
$105,759
$76,027
$24,407
$135,870
$40,483
$68,496
$53,034
$50,179
$41,996
$295,916
$100,739
$64,975
$64,537
$30,668
$47,068
$51,813
$57,778
$50,057
$125,589
$22,832
$58,551
$135,575
$34,809
$80,389
$58,046

In [26]:
# 16.Clean income_usd by removing currency symbols, commas, and invalid text,
# then convert it to a numeric column using pd.to_numeric().

df["income_usd"] = (df["income_usd"].astype(str).str.replace("$", "", regex=False).str.replace(",", "", regex=False))
df["income_usd"] = pd.to_numeric(df["income_usd"], errors="coerce")

df["income_usd"].dtype

dtype('float64')

In [27]:
# 17.Clean the Age column so values such as "35 years" become numeric values.

df['age'].value_counts()

age
18             92
18.0 years      8
unknown         8
thirty          5
??              4
               ..
37.19656193     1
46.3 years      1
26.83682375     1
25.2 years      1
59.25609491     1
Name: count, Length: 1523, dtype: int64

In [28]:
df['age'] = df['age'].str.replace(' years', '')
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['age'].head()

0    45.867417
1    47.765164
2          NaN
3    62.723578
4          NaN
Name: age, dtype: float64

In [29]:
# 18.Identify unrealistic age values using NumPy/Pandas and replace them with NaN.

import numpy as np

df.loc[df["age"] > 100, "age"] = np.nan
df.loc[df["age"] < 0, "age"] = np.nan

df["age"].isna().sum()

np.int64(351)

In [31]:
# 19.Clean the credit_score column by removing text such as "pts" and converting
# the column to numeric.

df['credit_score'] = df['credit_score'].str.replace('pts', '') 
df['credit_score'] = pd.to_numeric(df['credit_score'], errors='coerce') 
df['credit_score'].head()

0    660.562918
1    838.000000
2    613.132775
3    720.236986
4    549.183252
Name: credit_score, dtype: float64

In [ ]:
# 20.Detect outliers in income_usd using the IQR method with NumPy/Pandas.

In [ ]:
# 21.Detect outliers in credit_score using the IQR method.

In [34]:
# 22.Detect suspicious values such as -999 and 99999 in tenure_years and satisfaction.

df[df['tenure_years'].isin([-999, 99999])]
df[df['satisfaction'].isin([-999, 99999])]

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
459,CUST-00484,44.969325,53926.90802,NaN,9.649929,7.0,-999.0,Mumbai,Enterprise,Female,NaN,0.0,2022-05-08,NaN,good
730,CUST-00215,34.067923,34151.42487,697.255770,2.008998,5.0,99999.0,Hyderabad,Consumer,Male,NaN,1.0,2021-08-07,NaN,good
788,CUST-01193,34.920151,NaN,797.594511,NaN,5.0,99999.0,Bengaluru,Smb,Female,NaN,0.0,2024-04-29,Google Ads,NaN
894,CUST-00637,35.720914,45890.95396,805.849093,1.206751,6.0,-999.0,Delhi,Enterprise,Female,0.0,0.0,11/10/2022,Unknown,NaN
948,CUST-00911,28.978930,NaN,636.000000,3.683234,NaN,99999.0,Pune,NaN,Male,0.0,1.0,2023-07-17,Website,late payment
1165,CUST-00674,22.198037,71822.09888,528.205800,5.782927,12.0,99999.0,Bengaluru,Consumer,Female,0.0,NaN,NaN,Social,NaN
1499,CUST-01004,45.606925,NaN,NaN,2.083318,3.0,-999.0,Kolkata,Smb,Male,0.0,0.0,2023-10-20,referral,NaN
1652,NaN,33.275106,37475.10034,NaN,4.345689,11.0,-999.0,Mumbai,Smb,Female,NaN,NaN,2022-02-15,Social,ok
1657,CUST-01891,50.294152,28185.47045,827.000000,3.909337,6.0,99999.0,Hyderabad,Enterprise,Male,0.0,NaN,10/04/2026,WEB,late payment
1872,CUST-01181,22.154132,31958.96865,569.916053,6.100963,10.0,99999.0,Pune,Smb,Female,1.0,0.0,2024-04-17,Social,urgent

In [35]:
# 23.Replace invalid/suspicious numerical values with NaN.

df['tenure_years'] = df['tenure_years'].replace([-999, 99999], np.nan)
df['satisfaction'] = df['satisfaction'].replace([-999, 99999], np.nan)
df[['tenure_years', 'satisfaction']].head()

   tenure_years  satisfaction
0      5.274076      3.382150
1      5.632826           NaN
2           NaN      4.195157
3      2.029634           NaN
4      2.648626      3.117326

In [36]:
# 24.Fill missing numerical values using the median of each numerical column.

num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())
df[num_cols].isnull().sum()

age               0
income_usd        0
credit_score      0
tenure_years      0
monthly_visits    0
satisfaction      0
is_active         0
churn_flag        0
dtype: int64

In [37]:
# 25.Fill missing categorical values using the mode of each categorical column.

cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])
df[cat_cols].isnull().sum()

customer_id         0
city                0
customer_segment    0
gender              0
signup_date         0
lead_source         0
notes_text          0
dtype: int64

In [38]:
# 26.Clean the signup_date column, which contains multiple date formats and
# invalid dates, and convert it to Pandas datetime.

df['signup_date'] = pd.to_datetime(df['signup_date'], errors='coerce')
df['signup_date'].head()

0   2026-03-11
1          NaT
2   2024-09-20
3   2023-07-12
4   2024-08-06
Name: signup_date, dtype: datetime64[ns]

In [39]:
# 27.Find rows where signup_date could not be converted into a valid date.

invalid_dates = df[df['signup_date'].isna()]
invalid_dates

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
1,CUST-00354,47.765164,61312.83129,838.000000,5.632826,9.0,3.742125,Hyderabad,Consumer,Male,1.0,0.0,NaT,website,follow-up needed
5,CUST-01274,37.944404,44696.00000,647.914390,1.700044,12.0,3.742125,Bengaluru,Smb,Male,1.0,1.0,NaT,referral,follow-up needed
7,CUST-01732,37.630010,80888.86264,850.000000,4.489813,11.0,3.742125,Pune,Consumer,Female,0.0,0.0,NaT,referral,good customer
11,CUST-01293,37.944404,56124.71172,744.408134,6.966279,1.0,3.990252,Bengaluru,Smb,Female,1.0,0.0,NaT,Website,???
13,CUST-00585,37.944404,56124.71172,647.914390,2.786554,8.0,3.742125,Mumbai,Smb,Male,1.0,0.0,NaT,referral,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,CUST-01688,40.975371,69577.95359,705.831623,4.683845,4.0,2.808807,Mumbai,Consumer,Male,0.0,1.0,NaT,???,good
1982,CUST-00872,25.905285,37890.55358,674.000000,0.923243,8.0,3.427559,Chennai,Consumer,Male,1.0,0.0,NaT,Email,complaint!!!
1983,CUST-01124,35.170048,74269.07836,703.564221,4.683845,7.0,3.486785,Pune,Smb,Female,0.0,0.0,NaT,referral,normal
1986,CUST-01483,39.375013,94014.27980,563.745109,3.605231,7.0,3.726318,Delhi,Enterprise,Female,0.0,0.0,NaT,referral,normal
1988,CUST-01239,45.400000,90683.09594,719.914379,7.362245,9.0,4.418195,Hyderabad,Enterprise,Male,1.0,0.0,NaT,Referral,good

In [40]:
# 28.Clean the lead_source column by standardizing values such as Website,
# website, WEB, Referral, referral , Google Ads, and google_ads.

df['lead_source'] = df['lead_source'].str.strip().str.lower()
df['lead_source'] = df['lead_source'].replace({
    'web': 'website',
    'google_ads': 'google ads'})
df['lead_source'].value_counts()

lead_source
referral      708
website       382
email         264
google ads    242
???           141
social        140
unknown       123
Name: count, dtype: int64

In [43]:
# 29.Create a final cleaned DataFrame containing:
# • cleaned column names
# • no duplicate IDs
# • standardized categorical values
# • numeric columns converted to numeric types
# • invalid values converted to NaN
# • missing values handled
# • detected outliers handled

clean_df = df.copy()
clean_df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [44]:
clean_df = clean_df.drop_duplicates(subset='customer_id')
num_cols = clean_df.select_dtypes(include='number').columns
for col in num_cols:
    clean_df[col] = pd.to_numeric(clean_df[col], errors='coerce')

In [45]:
clean_df['tenure_years'] = clean_df['tenure_years'].replace([-999, 99999], np.nan)
clean_df['satisfaction'] = clean_df['satisfaction'].replace([-999, 99999], np.nan)

In [47]:
clean_df['credit_score'] = clean_df['credit_score'].astype(str)
clean_df['credit_score'] = clean_df['credit_score'].str.replace('pts', '')
clean_df['credit_score'] = pd.to_numeric( clean_df['credit_score'], errors='coerce' )

In [48]:
clean_df['lead_source'] = clean_df['lead_source'].str.strip().str.lower()
clean_df['lead_source'] = clean_df['lead_source'].replace({ 'web': 'website', 'google_ads': 'google ads' })

In [49]:
clean_df['signup_date'] = pd.to_datetime( clean_df['signup_date'], errors='coerce' )

In [50]:
num_cols = clean_df.select_dtypes(include='number').columns
for col in num_cols:
    clean_df[col] = clean_df[col].fillna(clean_df[col].median())

In [51]:
cat_cols = clean_df.select_dtypes(include='object').columns
for col in cat_cols:
    clean_df[col] = clean_df[col].fillna(clean_df[col].mode()[0])

In [52]:
for col in num_cols:
    Q1 = clean_df[col].quantile(0.25)
    Q3 = clean_df[col].quantile(0.75)
    IQR = Q3 - Q1 
    lower = Q1 - 1.5 * IQR 
    upper = Q3 + 1.5 * IQR 
    clean_df[col] = clean_df[col].clip(lower, upper)

In [53]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1980 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1980 non-null   object
 1   age               1980 non-null   float64
 2   income_usd        1980 non-null   float64
 3   credit_score      1980 non-null   float64
 4   tenure_years      1980 non-null   float64
 5   monthly_visits    1980 non-null   float64
 6   satisfaction      1980 non-null   float64
 7   city              1980 non-null   object
 8   customer_segment  1980 non-null   object
 9   gender            1980 non-null   object
 10  is_active         1980 non-null   float64
 11  churn_flag        1980 non-null   float64
 12  signup_date       1576 non-null   datetime64[ns]
 13  lead_source       1980 non-null   object
 14  notes_text        1980 non-null   object
dtypes: datetime64[ns](1), float64(8), object(6)
memory usage: 247.5+ KB

In [54]:
clean_df.head()

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.867417,28198.41033,660.562918,5.274076,5.0,3.382150,Pune,Consumer,Male,1.0,0.0,2026-03-11,referral,normal
1,CUST-00354,47.765164,61312.83129,828.660843,5.632826,9.0,3.742125,Hyderabad,Consumer,Male,1.0,0.0,NaT,website,follow-up needed
2,CUST-01334,37.944404,44199.67124,613.132775,4.683845,8.0,4.195157,Mumbai,Consumer,Male,1.0,0.0,2024-09-20,email,normal
3,CUST-00906,60.970428,56259.90961,720.236986,2.029634,4.0,3.742125,Chennai,Enterprise,Male,0.0,0.0,2023-07-12,website,normal
4,CUST-01290,37.944404,31238.64196,549.183252,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,1.0,0.0,2024-08-06,referral,???

In [55]:
# 30.Perform a final data-quality audit using Pandas and NumPy:
# • Check remaining missing values
# • Check duplicate rows
# • Check duplicate customer IDs
# • Check data types
# • Check numerical ranges
# • Check unique categorical values
# • Confirm the final dataset is ready for analysis/ML

clean_df.isnull().sum()

customer_id           0
age                   0
income_usd            0
credit_score          0
tenure_years          0
monthly_visits        0
satisfaction          0
city                  0
customer_segment      0
gender                0
is_active             0
churn_flag            0
signup_date         404
lead_source           0
notes_text            0
dtype: int64

In [56]:
clean_df.duplicated().sum()

np.int64(0)

In [57]:
clean_df['customer_id'].duplicated().sum()

np.int64(0)

In [58]:
clean_df.dtypes

customer_id                 object
age                        float64
income_usd                 float64
credit_score               float64
tenure_years               float64
monthly_visits             float64
satisfaction               float64
city                        object
customer_segment            object
gender                      object
is_active                  float64
churn_flag                 float64
signup_date         datetime64[ns]
lead_source                 object
notes_text                  object
dtype: object

In [59]:
clean_df.select_dtypes(include=np.number).describe()

,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,is_active,churn_flag
count,1980.000000,1980.000000,1980.000000,1980.000000,1980.000000,1980.000000,1980.000000,1980.0
mean,37.714175,60550.743965,647.879304,5.289207,6.034343,3.710671,0.594949,0.0
std,10.221241,25472.051701,79.187331,3.002149,2.111790,0.725385,0.491026,0.0
min,18.000000,10198.638780,470.860153,0.073142,2.000000,2.040151,0.000000,0.0
25%,31.644084,43683.817270,605.035412,3.170620,5.000000,3.299627,0.000000,0.0
50%,37.944404,56124.711720,647.914390,4.683845,6.000000,3.742125,1.000000,0.0
75%,43.374622,72229.597040,694.485584,6.881265,7.000000,4.139277,1.000000,0.0
max,60.970428,115048.266695,828.660843,12.447232,10.000000,5.000000,1.000000,0.0

In [60]:
cat_cols = clean_df.select_dtypes(include='object').columns

for col in cat_cols:
    print(col, ":", clean_df[col].unique())

customer_id : ['CUST-01861' 'CUST-00354' 'CUST-01334' ... 'CUST-00861' 'CUST-01460'
 'CUST-01127']
city : ['Pune' 'Hyderabad' 'Mumbai' 'Chennai' 'Bengaluru' 'Kolkata' 'Delhi']
customer_segment : ['Consumer' 'Enterprise' 'Smb' 'Unknown']
gender : ['Male' 'Female']
lead_source : ['referral' 'website' 'email' 'google ads' 'social' 'unknown' '???']
notes_text : ['normal' 'follow-up needed' '???' 'good customer' 'complaint!!!' 'ok'
 'VIP' 'urgent' 'good' 'late payment']

In [61]:
clean_df.shape

(1980, 15)