In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("C:\\Users\\bhoom\\Downloads\\Customer_datasets - Customer_datasets.csv")
df.head()

,Customer_ID,Name,Age,Salary,Join_Date,Department,Performance_Score,Email,City,Gender,Is_Active
0,1357,Customer_1357,27,29664.12,2022-06-14,HR,69.1,user1356@outlook.com,Houston,Male,FALSE
1,985,Customer_985,27,47373.17,NaN,Marketing,1.9,user984@yahoo.com,Dallas,Female,FALSE
2,1828,Customer_860,62,63380.36,20170530,Operations,78.2,user859@gmail.com,NaN,Male,NaN
3,1985,Customer_1985,thirty,56746.57,2016-12-19 00:00:00,IT,85.8,user1984@company.com,New York,Male,TRUE
4,1294,Customer_1294,41,61654.21,2019-03-12,Finance,82.5,user1293@gmail.com,NEW YORK,Other,TRUE

In [37]:
# 1. How many missing values are there in each column? Which column has the highest
# number of missing values?

df.columns

Index(['Customer_ID', 'Name', 'Age', 'Salary', 'Join_Date', 'Department',
       'Performance_Score', 'Email', 'City', 'Gender', 'Is_Active'],
      dtype='object')

In [38]:
df.isnull().sum()

Customer_ID            0
Name                 145
Age                   84
Salary                97
Join_Date            254
Department            51
Performance_Score     39
Email                 49
City                  43
Gender                34
Is_Active             25
dtype: int64

In [39]:
df.isnull().sum().idxmax()

'Join_Date'

In [40]:
# 2. What percentage of rows have at least one missing value?

(df.isna().sum()/1535)*100

Customer_ID           0.000000
Name                  9.446254
Age                   5.472313
Salary                6.319218
Join_Date            16.547231
Department            3.322476
Performance_Score     2.540717
Email                 3.192182
City                  2.801303
Gender                2.214984
Is_Active             1.628664
dtype: float64

In [41]:
# 3. Drop all rows that have more than 3 missing values. How many rows remain?

df = df[df.isnull().sum(axis=1) < 3]
df

,Customer_ID,Name,Age,Salary,Join_Date,Department,Performance_Score,Email,City,Gender,Is_Active
0,1357,Customer_1357,27,29664.12,2022-06-14,HR,69.1,user1356@outlook.com,Houston,Male,FALSE
1,985,Customer_985,27,47373.17,NaN,Marketing,1.9,user984@yahoo.com,Dallas,Female,FALSE
2,1828,Customer_860,62,63380.36,20170530,Operations,78.2,user859@gmail.com,NaN,Male,NaN
3,1985,Customer_1985,thirty,56746.57,2016-12-19 00:00:00,IT,85.8,user1984@company.com,New York,Male,TRUE
4,1294,Customer_1294,41,61654.21,2019-03-12,Finance,82.5,user1293@gmail.com,NEW YORK,Other,TRUE
...,...,...,...,...,...,...,...,...,...,...,...
2025,1131,Customer_1131,74,46818.31,2018-08-09,Marketing,46.8,user1130@outlook.com,Phoenix,Other,FALSE
2026,1295,Customer_1295,72,64255.45,2017-08-23,Support,Excellent,user1294@outlook.com,San Jose,Male,FALSE
2027,861,Customer_861,21,NaN,2019-10-28,Finance,43.7,user860@gmail.com,Los Angeles,Other,TRUE
2028,1460,Customer_1460,69,46179.42,2020-01-06,IT,17.5,user1459@outlook.com,Los Angeles,Female,FALSE
2029,1127,Customer_1127,65,58869.43,2020-01-17,Finance,47.4,user1126@outlook.com,San Jose,Male,FALSE

In [42]:
# 4. How many exact duplicate rows are present in the dataset?

df.duplicated().sum()

np.int64(30)

In [43]:
# 5. How many duplicate Customer_IDs are there? Keep only the first occurrence of each Customer_ID.

df["Customer_ID"].duplicated().sum()

np.int64(76)

In [44]:
df = df.drop_duplicates("Customer_ID", keep="first")

In [45]:
df["Customer_ID"].duplicated().sum()

np.int64(0)

In [46]:
# 6. Convert the Age column to numeric. How many values could not be converted (became NaN)?

df = df.copy()

df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [47]:
df["Age"].isna().sum()

np.int64(114)

In [48]:
# 7. After converting Age to numeric, identify and remove outliers using the IQR method.
# How many outliers were removed?

Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = (df["Age"] < lower) | (df["Age"] > upper)

print("Outliers removed:", outliers.sum())

df = df[outliers].copy()

Outliers removed: 11

In [49]:
# 8. Replace remaining missing values in Age with the median age.

df["Age"] = df["Age"].fillna(df["Age"].median())
df["Age"].isna().sum()

np.int64(0)

In [50]:
# 9. Clean the Salary column: remove currency symbols ($), commas, and convert
# everything possible to numeric. How many values remained non-numeric?

df["Salary"] = df["Salary"].astype(str).str.replace("$", "", regex=False)
df["Salary"] = df["Salary"].str.replace(",", "", regex=False)

df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

In [51]:
df["Salary"].isna().sum()

np.int64(1)

In [52]:
# 10. After cleaning, find the mean and median salary. Which one is more affected by
# outliers?

mean_salary = df["Salary"].mean()
median_salary = df["Salary"].median()

print("Mean Salary:", mean_salary)
print("Median Salary:", median_salary)

Mean Salary: 54961.01899999999
Median Salary: 53285.445

In [53]:
# 11. Convert the Join_Date column to proper datetime format. How many dates failed to parse?

df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")

C:\Users\bhoom\AppData\Local\Temp\ipykernel_7832\88490130.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")

In [54]:
df["Join_Date"].isna().sum()

np.int64(9)

In [55]:
# 12. Extract the year from the cleaned Join_Date. What is the most common joining year?

df["Join_Year"] = df["Join_Date"].dt.year

In [56]:
df["Join_Year"].mode()[0]

np.float64(2018.0)

In [57]:
# 13. Standardize the Department column (fix casing, trim spaces, fix common typos like
#“Sale” → “Sales”, “Financ” → “Finance”, etc.). How many unique departments remain
#after cleaning?

df["Department"] = df["Department"].astype(str).str.strip().str.title()

In [58]:
df["Department"].unique()

array(['Operations', 'Sales', 'Finance', 'Marketing', 'Financ'],
      dtype=object)

In [59]:
df=df.replace({"Department":{"Financ":"Finance"}})

In [60]:
df["Department"].unique()

array(['Operations', 'Sales', 'Finance', 'Marketing'], dtype=object)

In [66]:
# 14. Clean the City column (standardize names, fix “Los Angles” → “Los Angeles”, “NY” →
#“New York”, “Philly” → “Philadelphia”, etc.). List the final unique cities.

df["City"] = df["City"].astype(str).str.strip().str.title()

In [67]:
df["City"].unique()

array(['San Jose', 'Chicago', 'San Diego', 'New York', 'Houston',
       'Los Angeles', 'Philadelphia', 'San Antonio'], dtype=object)

In [68]:
# 15. Standardize the Gender column so it only contains “Male”, “Female”, and “Other”.
#How many records were changed?

df["Gender"].unique()

array(['Male', 'Other', nan, 'Female'], dtype=object)

In [69]:
# 16. Convert Performance_Score to numeric. Replace non-numeric values with NaN, then
#fill missing scores with the mean.

df["Performance_Score"] = pd.to_numeric(
    df["Performance_Score"],
    errors="coerce"
)

df["Performance_Score"] = df["Performance_Score"].fillna(
    df["Performance_Score"].mean()
)

In [70]:
df["Performance_Score"].isna().sum()

np.int64(0)

In [71]:
# 17. Clean the Is_Active column so it becomes a proper boolean (True/False). Map values
#like “Yes”, “Y”, “1”, “Active”, “true” → True and “No”, “N”, “0”, “Inactive”, “false” →
#False.

df["Is_Active"].unique()

array(['TRUE', 'FALSE'], dtype=object)

In [74]:
df=df.replace({"Is_Active":{"TRUE":True,
                            "FALSE":False}})

In [75]:
df["Is_Active"].unique()

array(['True', 'False'], dtype=object)

In [77]:
# 18. Flag invalid email addresses (those that do not contain “@” or have incomplete
# domains). How many invalid emails are there?

df["Email"].unique()

array(['user438@gmail.com', 'user270@gmail.com', 'user497@yahoo.com',
       'user1653@outlook.com', 'user841@company.com',
       'user145@outlook.com', 'user1370@yahoo.com',
       'user1769@company.com', 'user487@company.com', 'user725@yahoo.com',
       'user1180@outlook.com'], dtype=object)

In [79]:
# 19. Clean the Name column: replace empty strings, “N/A”, and “Unknown” with NaN.
#How many names are still missing after this step?

df["Name"].unique()

array(['Customer_439', 'Customer_271', 'Customer_498', 'Customer_1654',
       'Customer_842', 'Customer_146', 'Customer_1371', 'Customer_1770',
       'Customer_488', 'Customer_726', 'Customer_1181'], dtype=object)

In [80]:
# 20. Perform a complete data cleaning pipeline on the entire dataset and save the
#cleaned version as cleaned_dataset.csv. Report the final shape of the cleaned dataset
#and briefly describe the main cleaning steps you applied.

df

,Customer_ID,Name,Age,Salary,Join_Date,Department,Performance_Score,Email,City,Gender,Is_Active,Join_Year
175,439,Customer_439,200.0,NaN,2020-01-13,Operations,80.30,user438@gmail.com,San Jose,Male,True,2020.0
240,271,Customer_271,999.0,35552.47,NaT,Sales,65.40,user270@gmail.com,Chicago,Other,False,NaN
571,498,Customer_498,200.0,46843.31,NaT,Finance,62.03,user497@yahoo.com,San Diego,Male,False,NaN
766,1654,Customer_1654,200.0,74080.88,2018-05-03,Marketing,67.40,user1653@outlook.com,New York,NaN,False,2018.0
870,842,Customer_842,200.0,50921.32,NaT,Marketing,41.40,user841@company.com,Houston,Male,False,NaN
1221,146,Customer_146,150.0,51147.85,NaT,Finance,8.90,user145@outlook.com,Los Angeles,Female,False,NaN
1357,1371,Customer_1371,150.0,42419.66,NaT,Sales,79.10,user1370@yahoo.com,Chicago,Male,True,NaN
1375,1770,Customer_1770,200.0,55658.10,NaT,Operations,61.00,user1769@company.com,Philadelphia,Other,False,NaN
1485,488,Customer_488,999.0,55423.04,NaT,Finance,78.10,user487@company.com,Los Angeles,Other,True,NaN
1862,726,Customer_726,200.0,68135.74,NaT,Operations,61.40,user725@yahoo.com,San Antonio,Male,True,NaN
1902,1181,Customer_1181,999.0,69427.82,NaT,Operations,77.30,user1180@outlook.com,San Antonio,Male,False,NaN