In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("C:\\Users\\bhoom\\Downloads\\Dataset.csv", encoding="latin1")
df

C:\Users\bhoom\AppData\Local\Temp\ipykernel_16496\2017682602.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv("C:\\Users\\bhoom\\Downloads\\Dataset.csv", encoding="latin1")

,Product_name,Price,Rate,Review,Summary
0,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Simply awesome,it's really worth every single penny. it works...
1,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...
2,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Worth every penny,GREAT packaging by seller. As this was the mos...
3,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Fabulous!,Delivery was delayed by two days except this e...
4,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Nice product,A Good cooler by Crompton. The height of the c...
...,...,...,...,...,...
363256,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Terrific,Thanks
363257,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Terrific,Good
363258,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,5.0,Just wow!,Super
363259,"NIVEA Soft Light Moisturizer for Face, Hand & ...",??142,4.0,Worth the money,Good
363260,,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 363261 entries, 0 to 363260
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Product_name  363246 non-null  object
 1   Price         363245 non-null  object
 2   Rate          363245 non-null  object
 3   Review        363239 non-null  object
 4   Summary       361239 non-null  object
dtypes: object(5)
memory usage: 13.9+ MB

In [4]:
df.columns

Index(['Product_name', 'Price', 'Rate', 'Review', 'Summary'], dtype='object')

In [5]:
df.shape

(363261, 5)

## Product_name

In [6]:
df["Product_name"].isna().sum()

np.int64(15)

In [7]:
df = df.dropna(subset=["Product_name"])

In [8]:
df["Product_name"].isna().sum()

np.int64(0)

In [9]:
df["Product_name"].duplicated().sum()

np.int64(362071)

In [10]:
df["Product_name"].unique()

array(['Crompton 75 L Desert Air Cooler?\x98?\x98(White, Teal, ACGC-DAC751)',
       'Candes 12 L Room/Personal Air Cooler?\x98?\x98(White, Black, Elegant High Speed-Honey Comb Cooling Pad & Ice Chamber, Blower)',
       'Crompton 88 L Desert Air Cooler with Honeycomb Cooling Pad?\x98?\x98(White, Teal, ACGC-DAC881)',
       ...,
       'URBANYOG Hair Removal Cream Spray for Womens Hand, Leg & Under Arm, Painless Hair Removal Spray?\x98?\x98(200 ml)',
       'NIVEA Soft Light Moisturizer for Face, Hand & Body, Non-Sticky Cream with Vitamin E & Jojoba Oil?\x98?\x98(100 ml)',
       '\x1a'], shape=(1175,), dtype=object)

In [11]:
df["Product_name"].value_counts

<bound method IndexOpsMixin.value_counts of 0         Crompton 75 L Desert Air Cooler??(White, Tea...
1         Crompton 75 L Desert Air Cooler??(White, Tea...
2         Crompton 75 L Desert Air Cooler??(White, Tea...
3         Crompton 75 L Desert Air Cooler??(White, Tea...
4         Crompton 75 L Desert Air Cooler??(White, Tea...
                                ...
363256    NIVEA Soft Light Moisturizer for Face, Hand & ...
363257    NIVEA Soft Light Moisturizer for Face, Hand & ...
363258    NIVEA Soft Light Moisturizer for Face, Hand & ...
363259    NIVEA Soft Light Moisturizer for Face, Hand & ...
363260                                                    
Name: Product_name, Length: 363246, dtype: object>

## Price

In [12]:
df["Price"].isna().sum()

np.int64(1)

In [13]:
df= df.dropna(subset=["Price"])

In [14]:
df["Price"].isna().sum()

np.int64(0)

In [15]:
df["Price"].duplicated().sum()

np.int64(362536)

In [16]:
df["Price"].unique()

array(['\x9f??10,499', '\x9f??3,490', '\x9f??9,499', '\x9f??13,999',
       '\x9f??6,299', '\x9f??5,249', '\x9f??5,990', '\x9f??7,499',
       '\x9f??1,097', '\x9f??1,095', '\x9f??655', '\x9f??2,969',
       '\x9f??495', '\x9f??549', '\x9f??700', '\x9f??339', '\x9f??271',
       '\x9f??409', '\x9f??229', '\x9f??228', '\x9f??258', '\x9f??329',
       '\x9f??599', '\x9f??901', '\x9f??529', '\x9f??499', '\x9f??840',
       '\x9f??3,499', '\x9f??5,999', '\x9f??4,999', '\x9f??799',
       '\x9f??1,699', '\x9f??1,799', '\x9f??1,999', '\x9f??1,499',
       '\x9f??9,999', '\x9f??1,099', '\x9f??899', '\x9f??1,199',
       '\x9f??3,999', '\x9f??4,990', '\x9f??526', '\x9f??1,299',
       '\x9f??3,699', '\x9f??435', '\x9f??30,999', '???399', '???249',
       '???229', '???259', '???219', '???295', '???639', '???519',
       '???217', '???199', '???220', '??????322', '??????234',
       '??????342', '??????389', '??????143', '??????1,349', '??????499',
       '??????332', '??????299', '??????333', '??????541', '??????359',
       '??????566', '??????334', '??????325', '??????379', '??????259',
       '??????350', '??????999', '??????563', '??????341', '??????546',
       '??????338', '??????549', '??????540', '??????640', '??????616',
       '??????699', '??????1,499', '??????675', '??????678',
       '??????1,094', '??????475', '??????1,099', '???13,999', '???9,990',
       '???14,299', '???5,298', '???7,599', '???11,999', '\x9f??169',
       '\x9f??619', '\x9f??1,298', '\x9f??545', '\x9f??1,260',
       '\x9f??399', '\x9f??270', '\x9f??1,233', '\x9f??189', '\x9f??299',
       '\x9f??199', '\x9f??269', '\x9f??176', '\x9f??699', '\x9f??295',
       '\x9f??222', '\x9f??149', '\x9f??681', '\x9f??279', '\x9f??507',
       '\x9f??249', '\x9f??190', '\x9f??999', '\x9f??263', '\x9f??246',
       '\x9f??251', '\x9f??193', '\x9f??158', '\x9f??289', '\x9f??375',
       '\x9f??226', '\x9f??425', '\x9f??302', '\x9f??59', '\x9f??245',
       '\x9f??79', '\x9f??349', '\x9f??449', '\x9f??340', '\x9f??469',
       '\x9f??520', '\x9f??448', '\x9f??160', '\x9f??429', '\x9f??1,259',
       '\x9f??379', '\x9f??6,499', '\x9f??4,499', '\x9f??3,295',
       '\x9f??8,999', '\x9f??7,609', '\x9f??5,499', '\x9f??16,499',
       '\x9f??6,949', '\x9f??6,719', '???26,990', '???23,479',
       '???29,390', '???29,990', '???20,990', '???44,490', '???25,990',
       '???38,490', '???42,000', '???44,890', '???31,590', '???41,990',
       '???52,990', '???33,990', '???18,990', '???50,999', '???45,550',
       '\x9f??785', '\x9f??1,599', '\x9f??625', '???1,401', '???359',
       '???1,453', '???254', '???205', '???1,256', '???1,547', '???195',
       '???575', '???366', '???209', '???549', '???859', '???210',
       '???215', '???1,142', '???235', '???221', '\x9f??1,614',
       '\x9f??616', '\x9f??2,399', '\x9f??559', '\x9f??2,739',
       '\x9f??589', '\x9f??1,399', '\x9f??3,480', '\x9f??1,995',
       '\x9f??2,180', '\x9f??1,899', '\x9f??3,082', '\x9f??2,230',
       '\x9f??3,799', '\x9f??3,099', '\x9f??2,074', '\x9f??2,781',
       '\x9f??607', '\x9f??598', '\x9f??2,160', '\x9f??3,439',
       '\x9f??2,607', '\x9f??3,049', '\x9f??2,495', '\x9f??597',
       '\x9f??2,685', '\x9f??2,390', '\x9f??7,259', '\x9f??2,295',
       '\x9f??4,011', '\x9f??1,701', '\x9f??4,380', '\x9f??2,195',
       '\x9f??3,399', '\x9f??368', '\x9f??3,769', '\x9f??2,749',
       '\x9f??2,695', '\x9f??2,317', '\x9f??2,999', '\x9f??6,869',
       '\x9f??3,245', '\x9f??3,395', '\x9f??3,196', '\x9f??6,920',
       '\x9f??6,495', '\x9f??2,250', '\x9f??2,569', '\x9f??2,640',
       '\x9f??12,103', '\x9f??3,370', '\x9f??612', '\x9f??7,489',
       '\x9f??3,825', '\x9f??2,400', '\x9f??2,895', '\x9f??2,339',
       '\x9f??3,320', '???849', '???699',
       'Pigeon Favourite Electric Kettle????(1.5 L, Silver, Black)',
       '\x9f??109', '\x9f??260', '\x9f??1,448', '\x9f??3,569',
       '\x9f??1,349', '\x9f??2,879', '\x9f??1,329', '\x9f??310',
       '\x9f??268', '\x9f??214', '\x9f??155', '\x9f??125', '\x9f??225',
       '\x9f??240', '\x9f??233', '\x9f??195', '\x9f??173', '\x9f??277',
       '\x9f??253', '\x9f??361', '\x9f??275', '\x9f??389', '\x9f??484',
       '\x9f??194', '\x9f??872', '\x9f??369', '\x9f??239', '\x9f??387',
       '\x9f??231', '\x9f??130', '\x9f??220', '\x9f??5,390',
       '\x9f??11,500', '\x9f??1,220', '\x9f??9,050', '\x9f??9,990',
       '\x9f??6,505', '\x9f??11,595', '\x9f??7,649', '\x9f??4,399',
       '\x9f??6,029', '\x9f??5,919', '\x9f??6,390', '\x9f??7,999',
       '\x9f??2,949', '\x9f??7,909', '\x9f??6,525', '\x9f??6,589',
       '\x9f??5,039', '\x9f??4,219', '\x9f??4,319', '\x9f??63,990',
       '\x9f??949', '\x9f??67,490', '\x9f??51,990', '\x9f??284',
       '\x9f??59,990', '\x9f??58,990', '\x9f??63,600', '\x9f??749',
       '\x9f??3,595', '\x9f??4,497', '\x9f??7,129', '\x9f??809',
       '\x9f??4,998', '\x9f??718', '\x9f??791', '\x9f??356', '\x9f??377',
       '\x9f??385', '\x9f??365', '\x9f??6,999', '\x9f??113', '\x9f??216',
       '\x9f??1,278', '\x9f??159', '\x9f??145', '\x9f??168', '\x9f??298',
       '\x9f??179', '\x9f??219', '\x9f??450', '\x9f??719', '\x9f??259',
       '\x9f??203', '\x9f??631', '\x9f??797', '\x9f??230', '\x9f??497',
       '\x9f??2,125', '\x9f??440', '\x9f??890', '\x9f??674', '\x9f??476',
       '\x9f??565', '\x9f??178', '\x9f??585', '\x9f??292', '\x9f??522',
       '\x9f??300', '\x9f??343', '\x9f??175', '\x9f??184', '\x9f??850',
       '\x9f??1,898', '\x9f??881', '\x9f??505', '\x9f??248', '\x9f??290',
       '\x9f??364', '???290', '???494', '???293', '???659', '???404',
       '???436', '???257', '???405', '???299', '???684', '\x9f??224',
       '\x9f??227', '\x9f??480', '\x9f??427', '\x9f??236', '\x9f??209',
       '\x9f??690', '\x9f??649', '\x9f??335', '\x9f??285', 'product_name',
       '???5,079', '???6,591', '???4,699', '???6,195', '???4,199',
       '???5,959', '???7,299', '???8,499', '???529',
       'Bajaj DX 2 L/W Dry Iron',
       'Nova Plus Amaze NI 10 1100 W Dry Iron????(Grey & Turquoise)',
       '\x9f??1,290', '\x9f??501', '\x9f??5,190', '\x9f??417',
       '\x9f??2,590', '\x9f??6,498', '\x9f??13,049', '\x9f??3,268',
       '\x9f??2,709', '\x9f??12,999', '\x9f??1,383', '\x9f??2,995',
       '\x9f??470', '\x9f??606', '\x9f??464', '\x9f??645', '\x9f??475',
       '\x9f??517', '\x9f??1,119', '\x9f??678', '\x9f??489', '\x9f??513',
       '\x9f??629', '\x9f??357', '\x9f??849', '\x9f??739', '\x9f??3,959',
       '\x9f??2,692', '\x9f??3,661', '\x9f??3,035', '\x9f??777',
       '\x9f??9,950', '\x9f??474', '\x9f??648', '\x9f??66,990',
       '\x9f??33,990', '\x9f??86,990', '\x9f??46,999', '\x9f??27,490',
       '\x9f??46,990', '\x9f??38,990', '\x9f??1,804', '\x9f??5,890',
       '\x9f??1,709', '\x9f??2,970', '\x9f??6,690', '\x9f??15,490',
       '\x9f??11,999', '\x9f??8,890', '\x9f??5,414', '\x9f??792',
       '\x9f??4,823', '\x9f??359', '\x9f??5,022', '\x9f??218',
       '\x9f??197', '\x9f??303', '\x9f??1,549', '\x9f??185', '\x9f??188',
       '\x9f??665', '\x9f??10,890', '\x9f??14,190', '\x9f??4,498',
       '\x9f??6,099', '\x9f??2,099', '\x9f??3,249', '???2,709',
       '???1,399', '???3,399', '???2,299', '???1,899', '???343', '???649',
       '???499', '???1,299', '???449', '???329', '???2,199', '???269',
       '???155', '???284', '???127', '???278', '???171', '???136',
       '???179', '???7,499', '\x9f??2,190', '\x9f??2,690', '\x9f??323',
       '\x9f??315', '\x9f??7,493', '\x9f??5,993', '\x9f??988',
       '\x9f??150', '\x9f??2,152', '\x9f??170', '\x9f??14,146',
       '\x9f??4,715', '\x9f??5,790', '\x9f??3,059', '\x9f??8,449',
       '\x9f??8,590', '\x9f??555', '\x9f??7,599', '\x9f??415',
       '\x9f??4,293', '\x9f??3,307', '\x9f??3,149', '\x9f??2,499',
       '\x9f??5,299', '\x9f??10,799', '\x9f??4,299', '\x9f??569',
       '\x9f??577', '\x9f??247', '\x9f??897', '\x9f??324', '???1,375',
       '???1,149', '???852', '???615', '???828', '???1,199', '???912',
       '???421', '???809', '???999', '???789', '???489', '???669',
       '\x9f??24,490', '\x9f??16,490', '???348', '???945', '???315',
       '???980', '???495', '???260', '???369', '???1,249', '???599',
       '\x9f??1,565', '\x9f??2,699', '\x9f??1,149', '\x9f??1,449',
       '\x9f??1,889', '\x9f??2,133', '\x9f??1,049', '\x9f??1,469',
       '\x9f??2,299', '\x9f??2,599', '\x9f??19,999', '\x9f??2,600',
       '\x9f??14,599', '\x9f??2,485', '\x9f??4,599', '\x9f??1,595',
       '\x9f??2,875', '\x9f??3,558', '\x9f??16,299', '\x9f??2,298',
       '\x9f??5,199', '\x9f??2,799', '\x9f??6,399', '\x9f??1,350',
       '\x9f??478', '\x9f??423', '\x9f??8,499', '\x9f??989',
       '\x9f??2,990', '\x9f??2,490', '\x9f??2,345', '\x9f??388',
       '\x9f??759', '\x9f??2,199', '\x9f??766', '\x9f??134', '\x9f??725',
       '\x9f??200', '\x9f??198', '\x9f??590', '\x9f??319', '\x9f??325',
       '\x9f??29,900', '\x9f??27,999', '\x9f??49,999', '\x9f??22,999',
       '\x9f??14,999', '\x9f??20,999', '\x9f??14,499', '\x9f??47,900',
       '\x9f??17,999', '\x9f??18,499', '\x9f??7,399', '\x9f??32,999',
       '\x9f??41,900', '\x9f??25,999', '\x9f??28,999', '\x9f??57,900',
       '\x9f??16,999', '\x9f??69,900', '\x9f??49,900', '\x9f??21,999',
       '\x9f??13,450', '\x9f??63,900', '\x9f??68,900', '\x9f??15,999',
       '\x9f??54,900', '\x9f??3,514', '\x9f??13,499', '\x9f??74,900',
       '\x9f??39,900', '\x9f??2,912', '\x9f??1,639', '\x9f??2,443',
       '\x9f??2,780', '\x9f??650', '\x9f??3,299', '\x9f??9,490',
       '\x9f??4,961', '\x9f??7,990', '\x9f??4,690', '\x9f??7,490',
       '\x9f??30,997', '\x9f??3,672', '\x9f??4,199', '\x9f??8,599',
       '\x9f??2,300', '\x9f??13,145', '\x9f??3,607', '\x9f??1,423',
       '\x9f??3,763', '\x9f??5,437', '\x9f??32,990', '\x9f??13,810',
       '\x9f??4,490', '\x9f??12,457', '\x9f??4,940', '\x9f??9,590',
       '\x9f??2,550', '\x9f??5,166', '\x9f??1,994', '\x9f??6,790',
       '\x9f??3,890', '\x9f??4,660', '\x9f??26,990', '\x9f??8,990',
       '\x9f??12,990', '\x9f??7,899', '\x9f??6,290', '\x9f??288',
       '\x9f??164', '\x9f??235', '\x9f??181', '\x9f??144', '\x9f??250',
       '\x9f??210', '\x9f??186', '\x9f??212', '\x9f??344', '\x9f??294',
       '\x9f??205', '\x9f??679', '\x9f??537', '\x9f??293', '\x9f??636',
       '\x9f??254', '\x9f??143', '\x9f??252', '\x9f??1,284', '\x9f??540',
       '\x9f??579', '\x9f??1,353', '???3,999', '???2,999', '???834',
       '???6,387', '???2,651', '???749', '???1,550', '???488', '???899',
       '???493', '???427', '\x9f??16,990', '\x9f??14,790', '\x9f??8,490',
       '\x9f??2,184', '\x9f??8,199', '\x9f??4,687', '\x9f??7,799',
       '\x9f??14,299', '???7,079', '???5,299', '???4,330', '???5,300',
       '???4,000', '???10,000', '???10,790', '???9,190', '???3,599',
       '???4,999', '???8,699', '???5,149', '???4,084', '???9,799',
       '???7,690', '???4,899', '???3,746', '???4,396', '\x9f??237',
       '\x9f??314', '\x9f??441', '\x9f??142'], dtype=object)

In [17]:
df["Price"].dtypes

dtype('O')

In [18]:
df["Price"] = df["Price"].str.replace(r"[^0-9]", "", regex=True)
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

In [19]:
df["Price"].unique()

array([1.0499e+04, 3.4900e+03, 9.4990e+03, 1.3999e+04, 6.2990e+03,
       5.2490e+03, 5.9900e+03, 7.4990e+03, 1.0970e+03, 1.0950e+03,
       6.5500e+02, 2.9690e+03, 4.9500e+02, 5.4900e+02, 7.0000e+02,
       3.3900e+02, 2.7100e+02, 4.0900e+02, 2.2900e+02, 2.2800e+02,
       2.5800e+02, 3.2900e+02, 5.9900e+02, 9.0100e+02, 5.2900e+02,
       4.9900e+02, 8.4000e+02, 3.4990e+03, 5.9990e+03, 4.9990e+03,
       7.9900e+02, 1.6990e+03, 1.7990e+03, 1.9990e+03, 1.4990e+03,
       9.9990e+03, 1.0990e+03, 8.9900e+02, 1.1990e+03, 3.9990e+03,
       4.9900e+03, 5.2600e+02, 1.2990e+03, 3.6990e+03, 4.3500e+02,
       3.0999e+04, 3.9900e+02, 2.4900e+02, 2.5900e+02, 2.1900e+02,
       2.9500e+02, 6.3900e+02, 5.1900e+02, 2.1700e+02, 1.9900e+02,
       2.2000e+02, 3.2200e+02, 2.3400e+02, 3.4200e+02, 3.8900e+02,
       1.4300e+02, 1.3490e+03, 3.3200e+02, 2.9900e+02, 3.3300e+02,
       5.4100e+02, 3.5900e+02, 5.6600e+02, 3.3400e+02, 3.2500e+02,
       3.7900e+02, 3.5000e+02, 9.9900e+02, 5.6300e+02, 3.4100e+02,
       5.4600e+02, 3.3800e+02, 5.4000e+02, 6.4000e+02, 6.1600e+02,
       6.9900e+02, 6.7500e+02, 6.7800e+02, 1.0940e+03, 4.7500e+02,
       9.9900e+03, 1.4299e+04, 5.2980e+03, 7.5990e+03, 1.1999e+04,
       1.6900e+02, 6.1900e+02, 1.2980e+03, 5.4500e+02, 1.2600e+03,
       2.7000e+02, 1.2330e+03, 1.8900e+02, 2.6900e+02, 1.7600e+02,
       2.2200e+02, 1.4900e+02, 6.8100e+02, 2.7900e+02, 5.0700e+02,
       1.9000e+02, 2.6300e+02, 2.4600e+02, 2.5100e+02, 1.9300e+02,
       1.5800e+02, 2.8900e+02, 3.7500e+02, 2.2600e+02, 4.2500e+02,
       3.0200e+02, 5.9000e+01, 2.4500e+02, 7.9000e+01, 3.4900e+02,
       4.4900e+02, 3.4000e+02, 4.6900e+02, 5.2000e+02, 4.4800e+02,
       1.6000e+02, 4.2900e+02, 1.2590e+03, 6.4990e+03, 4.4990e+03,
       3.2950e+03, 8.9990e+03, 7.6090e+03, 5.4990e+03, 1.6499e+04,
       6.9490e+03, 6.7190e+03, 2.6990e+04, 2.3479e+04, 2.9390e+04,
       2.9990e+04, 2.0990e+04, 4.4490e+04, 2.5990e+04, 3.8490e+04,
       4.2000e+04, 4.4890e+04, 3.1590e+04, 4.1990e+04, 5.2990e+04,
       3.3990e+04, 1.8990e+04, 5.0999e+04, 4.5550e+04, 7.8500e+02,
       1.5990e+03, 6.2500e+02, 1.4010e+03, 1.4530e+03, 2.5400e+02,
       2.0500e+02, 1.2560e+03, 1.5470e+03, 1.9500e+02, 5.7500e+02,
       3.6600e+02, 2.0900e+02, 8.5900e+02, 2.1000e+02, 2.1500e+02,
       1.1420e+03, 2.3500e+02, 2.2100e+02, 1.6140e+03, 2.3990e+03,
       5.5900e+02, 2.7390e+03, 5.8900e+02, 1.3990e+03, 3.4800e+03,
       1.9950e+03, 2.1800e+03, 1.8990e+03, 3.0820e+03, 2.2300e+03,
       3.7990e+03, 3.0990e+03, 2.0740e+03, 2.7810e+03, 6.0700e+02,
       5.9800e+02, 2.1600e+03, 3.4390e+03, 2.6070e+03, 3.0490e+03,
       2.4950e+03, 5.9700e+02, 2.6850e+03, 2.3900e+03, 7.2590e+03,
       2.2950e+03, 4.0110e+03, 1.7010e+03, 4.3800e+03, 2.1950e+03,
       3.3990e+03, 3.6800e+02, 3.7690e+03, 2.7490e+03, 2.6950e+03,
       2.3170e+03, 2.9990e+03, 6.8690e+03, 3.2450e+03, 3.3950e+03,
       3.1960e+03, 6.9200e+03, 6.4950e+03, 2.2500e+03, 2.5690e+03,
       2.6400e+03, 1.2103e+04, 3.3700e+03, 6.1200e+02, 7.4890e+03,
       3.8250e+03, 2.4000e+03, 2.8950e+03, 2.3390e+03, 3.3200e+03,
       8.4900e+02, 1.5000e+01, 1.0900e+02, 2.6000e+02, 1.4480e+03,
       3.5690e+03, 2.8790e+03, 1.3290e+03, 3.1000e+02, 2.6800e+02,
       2.1400e+02, 1.5500e+02, 1.2500e+02, 2.2500e+02, 2.4000e+02,
       2.3300e+02, 1.7300e+02, 2.7700e+02, 2.5300e+02, 3.6100e+02,
       2.7500e+02, 4.8400e+02, 1.9400e+02, 8.7200e+02, 3.6900e+02,
       2.3900e+02, 3.8700e+02, 2.3100e+02, 1.3000e+02, 5.3900e+03,
       1.1500e+04, 1.2200e+03, 9.0500e+03, 6.5050e+03, 1.1595e+04,
       7.6490e+03, 4.3990e+03, 6.0290e+03, 5.9190e+03, 6.3900e+03,
       7.9990e+03, 2.9490e+03, 7.9090e+03, 6.5250e+03, 6.5890e+03,
       5.0390e+03, 4.2190e+03, 4.3190e+03, 6.3990e+04, 9.4900e+02,
       6.7490e+04, 5.1990e+04, 2.8400e+02, 5.9990e+04, 5.8990e+04,
       6.3600e+04, 7.4900e+02, 3.5950e+03, 4.4970e+03, 7.1290e+03,
       8.0900e+02, 4.9980e+03, 7.1800e+02, 7.9100e+02, 3.5600e+02,
       3.7700e+02, 3.8500e+02, 3.6500e+02, 6.9990e+03, 1.1300e+02,
       2.1600e+02, 1.2780e+03, 1.5900e+02, 1.4500e+02, 1.6800e+02,
       2.9800e+02, 1.7900e+02, 4.5000e+02, 7.1900e+02, 2.0300e+02,
       6.3100e+02, 7.9700e+02, 2.3000e+02, 4.9700e+02, 2.1250e+03,
       4.4000e+02, 8.9000e+02, 6.7400e+02, 4.7600e+02, 5.6500e+02,
       1.7800e+02, 5.8500e+02, 2.9200e+02, 5.2200e+02, 3.0000e+02,
       3.4300e+02, 1.7500e+02, 1.8400e+02, 8.5000e+02, 1.8980e+03,
       8.8100e+02, 5.0500e+02, 2.4800e+02, 2.9000e+02, 3.6400e+02,
       4.9400e+02, 2.9300e+02, 6.5900e+02, 4.0400e+02, 4.3600e+02,
       2.5700e+02, 4.0500e+02, 6.8400e+02, 2.2400e+02, 2.2700e+02,
       4.8000e+02, 4.2700e+02, 2.3600e+02, 6.9000e+02, 6.4900e+02,
       3.3500e+02, 2.8500e+02,        nan, 5.0790e+03, 6.5910e+03,
       4.6990e+03, 6.1950e+03, 4.1990e+03, 5.9590e+03, 7.2990e+03,
       8.4990e+03, 2.0000e+00, 1.0110e+05, 1.2900e+03, 5.0100e+02,
       5.1900e+03, 4.1700e+02, 2.5900e+03, 6.4980e+03, 1.3049e+04,
       3.2680e+03, 2.7090e+03, 1.2999e+04, 1.3830e+03, 2.9950e+03,
       4.7000e+02, 6.0600e+02, 4.6400e+02, 6.4500e+02, 5.1700e+02,
       1.1190e+03, 4.8900e+02, 5.1300e+02, 6.2900e+02, 3.5700e+02,
       7.3900e+02, 3.9590e+03, 2.6920e+03, 3.6610e+03, 3.0350e+03,
       7.7700e+02, 9.9500e+03, 4.7400e+02, 6.4800e+02, 6.6990e+04,
       8.6990e+04, 4.6999e+04, 2.7490e+04, 4.6990e+04, 3.8990e+04,
       1.8040e+03, 5.8900e+03, 1.7090e+03, 2.9700e+03, 6.6900e+03,
       1.5490e+04, 8.8900e+03, 5.4140e+03, 7.9200e+02, 4.8230e+03,
       5.0220e+03, 2.1800e+02, 1.9700e+02, 3.0300e+02, 1.5490e+03,
       1.8500e+02, 1.8800e+02, 6.6500e+02, 1.0890e+04, 1.4190e+04,
       4.4980e+03, 6.0990e+03, 2.0990e+03, 3.2490e+03, 2.2990e+03,
       2.1990e+03, 1.2700e+02, 2.7800e+02, 1.7100e+02, 1.3600e+02,
       2.1900e+03, 2.6900e+03, 3.2300e+02, 3.1500e+02, 7.4930e+03,
       5.9930e+03, 9.8800e+02, 1.5000e+02, 2.1520e+03, 1.7000e+02,
       1.4146e+04, 4.7150e+03, 5.7900e+03, 3.0590e+03, 8.4490e+03,
       8.5900e+03, 5.5500e+02, 4.1500e+02, 4.2930e+03, 3.3070e+03,
       3.1490e+03, 2.4990e+03, 5.2990e+03, 1.0799e+04, 4.2990e+03,
       5.6900e+02, 5.7700e+02, 2.4700e+02, 8.9700e+02, 3.2400e+02,
       1.3750e+03, 1.1490e+03, 8.5200e+02, 6.1500e+02, 8.2800e+02,
       9.1200e+02, 4.2100e+02, 7.8900e+02, 6.6900e+02, 2.4490e+04,
       1.6490e+04, 3.4800e+02, 9.4500e+02, 9.8000e+02, 1.2490e+03,
       1.5650e+03, 2.6990e+03, 1.4490e+03, 1.8890e+03, 2.1330e+03,
       1.0490e+03, 1.4690e+03, 2.5990e+03, 1.9999e+04, 2.6000e+03,
       1.4599e+04, 2.4850e+03, 4.5990e+03, 1.5950e+03, 2.8750e+03,
       3.5580e+03, 1.6299e+04, 2.2980e+03, 5.1990e+03, 2.7990e+03,
       6.3990e+03, 1.3500e+03, 4.7800e+02, 4.2300e+02, 9.8900e+02,
       2.9900e+03, 2.4900e+03, 2.3450e+03, 3.8800e+02, 7.5900e+02,
       7.6600e+02, 1.3400e+02, 7.2500e+02, 2.0000e+02, 1.9800e+02,
       5.9000e+02, 3.1900e+02, 2.9900e+04, 2.7999e+04, 4.9999e+04,
       2.2999e+04, 1.4999e+04, 2.0999e+04, 1.4499e+04, 4.7900e+04,
       1.7999e+04, 1.8499e+04, 7.3990e+03, 3.2999e+04, 4.1900e+04,
       2.5999e+04, 2.8999e+04, 5.7900e+04, 1.6999e+04, 6.9900e+04,
       4.9900e+04, 2.1999e+04, 1.3450e+04, 6.3900e+04, 6.8900e+04,
       1.5999e+04, 5.4900e+04, 3.5140e+03, 1.3499e+04, 7.4900e+04,
       3.9900e+04, 2.9120e+03, 1.6390e+03, 2.4430e+03, 2.7800e+03,
       6.5000e+02, 3.2990e+03, 9.4900e+03, 4.9610e+03, 7.9900e+03,
       4.6900e+03, 7.4900e+03, 3.0997e+04, 3.6720e+03, 8.5990e+03,
       2.3000e+03, 1.3145e+04, 3.6070e+03, 1.4230e+03, 3.7630e+03,
       5.4370e+03, 3.2990e+04, 1.3810e+04, 4.4900e+03, 1.2457e+04,
       4.9400e+03, 9.5900e+03, 2.5500e+03, 5.1660e+03, 1.9940e+03,
       6.7900e+03, 3.8900e+03, 4.6600e+03, 8.9900e+03, 1.2990e+04,
       7.8990e+03, 6.2900e+03, 2.8800e+02, 1.6400e+02, 1.8100e+02,
       1.4400e+02, 2.5000e+02, 1.8600e+02, 2.1200e+02, 3.4400e+02,
       2.9400e+02, 6.7900e+02, 5.3700e+02, 6.3600e+02, 2.5200e+02,
       1.2840e+03, 5.7900e+02, 1.3530e+03, 8.3400e+02, 6.3870e+03,
       2.6510e+03, 1.5500e+03, 4.8800e+02, 4.9300e+02, 1.6990e+04,
       1.4790e+04, 8.4900e+03, 2.1840e+03, 8.1990e+03, 4.6870e+03,
       7.7990e+03, 7.0790e+03, 4.3300e+03, 5.3000e+03, 4.0000e+03,
       1.0000e+04, 1.0790e+04, 9.1900e+03, 3.5990e+03, 8.6990e+03,
       5.1490e+03, 4.0840e+03, 9.7990e+03, 7.6900e+03, 4.8990e+03,
       3.7460e+03, 4.3960e+03, 2.3700e+02, 3.1400e+02, 4.4100e+02,
       1.4200e+02])

In [20]:
np.set_printoptions(suppress=True)
print(df["Price"].unique())

[ 10499.   3490.   9499.  13999.   6299.   5249.   5990.   7499.   1097.
   1095.    655.   2969.    495.    549.    700.    339.    271.    409.
    229.    228.    258.    329.    599.    901.    529.    499.    840.
   3499.   5999.   4999.    799.   1699.   1799.   1999.   1499.   9999.
   1099.    899.   1199.   3999.   4990.    526.   1299.   3699.    435.
  30999.    399.    249.    259.    219.    295.    639.    519.    217.
    199.    220.    322.    234.    342.    389.    143.   1349.    332.
    299.    333.    541.    359.    566.    334.    325.    379.    350.
    999.    563.    341.    546.    338.    540.    640.    616.    699.
    675.    678.   1094.    475.   9990.  14299.   5298.   7599.  11999.
    169.    619.   1298.    545.   1260.    270.   1233.    189.    269.
    176.    222.    149.    681.    279.    507.    190.    263.    246.
    251.    193.    158.    289.    375.    226.    425.    302.     59.
    245.     79.    349.    449.    340.    469.    520.    448.    160.
    429.   1259.   6499.   4499.   3295.   8999.   7609.   5499.  16499.
   6949.   6719.  26990.  23479.  29390.  29990.  20990.  44490.  25990.
  38490.  42000.  44890.  31590.  41990.  52990.  33990.  18990.  50999.
  45550.    785.   1599.    625.   1401.   1453.    254.    205.   1256.
   1547.    195.    575.    366.    209.    859.    210.    215.   1142.
    235.    221.   1614.   2399.    559.   2739.    589.   1399.   3480.
   1995.   2180.   1899.   3082.   2230.   3799.   3099.   2074.   2781.
    607.    598.   2160.   3439.   2607.   3049.   2495.    597.   2685.
   2390.   7259.   2295.   4011.   1701.   4380.   2195.   3399.    368.
   3769.   2749.   2695.   2317.   2999.   6869.   3245.   3395.   3196.
   6920.   6495.   2250.   2569.   2640.  12103.   3370.    612.   7489.
   3825.   2400.   2895.   2339.   3320.    849.     15.    109.    260.
   1448.   3569.   2879.   1329.    310.    268.    214.    155.    125.
    225.    240.    233.    173.    277.    253.    361.    275.    484.
    194.    872.    369.    239.    387.    231.    130.   5390.  11500.
   1220.   9050.   6505.  11595.   7649.   4399.   6029.   5919.   6390.
   7999.   2949.   7909.   6525.   6589.   5039.   4219.   4319.  63990.
    949.  67490.  51990.    284.  59990.  58990.  63600.    749.   3595.
   4497.   7129.    809.   4998.    718.    791.    356.    377.    385.
    365.   6999.    113.    216.   1278.    159.    145.    168.    298.
    179.    450.    719.    203.    631.    797.    230.    497.   2125.
    440.    890.    674.    476.    565.    178.    585.    292.    522.
    300.    343.    175.    184.    850.   1898.    881.    505.    248.
    290.    364.    494.    293.    659.    404.    436.    257.    405.
    684.    224.    227.    480.    427.    236.    690.    649.    335.
    285.     nan   5079.   6591.   4699.   6195.   4199.   5959.   7299.
   8499.      2. 101100.   1290.    501.   5190.    417.   2590.   6498.
  13049.   3268.   2709.  12999.   1383.   2995.    470.    606.    464.
    645.    517.   1119.    489.    513.    629.    357.    739.   3959.
   2692.   3661.   3035.    777.   9950.    474.    648.  66990.  86990.
  46999.  27490.  46990.  38990.   1804.   5890.   1709.   2970.   6690.
  15490.   8890.   5414.    792.   4823.   5022.    218.    197.    303.
   1549.    185.    188.    665.  10890.  14190.   4498.   6099.   2099.
   3249.   2299.   2199.    127.    278.    171.    136.   2190.   2690.
    323.    315.   7493.   5993.    988.    150.   2152.    170.  14146.
   4715.   5790.   3059.   8449.   8590.    555.    415.   4293.   3307.
   3149.   2499.   5299.  10799.   4299.    569.    577.    247.    897.
    324.   1375.   1149.    852.    615.    828.    912.    421.    789.
    669.  24490.  16490.    348.    945.    980.   1249.   1565.   2699.
   1449.   1889.   2133.   1049.   1469.   2599.  19999.   2600.  14599.
   2485.   4599.   1595.   2875.   3558.  16299.   2298.   5199.   2799.
   6399.   1350.    478.    423.    989.   2990.   2490.   2345.    388.
    759.    766.    134.    725.    200.    198.    590.    319.  29900.
  27999.  49999.  22999.  14999.  20999.  14499.  47900.  17999.  18499.
   7399.  32999.  41900.  25999.  28999.  57900.  16999.  69900.  49900.
  21999.  13450.  63900.  68900.  15999.  54900.   3514.  13499.  74900.
  39900.   2912.   1639.   2443.   2780.    650.   3299.   9490.   4961.
   7990.   4690.   7490.  30997.   3672.   8599.   2300.  13145.   3607.
   1423.   3763.   5437.  32990.  13810.   4490.  12457.   4940.   9590.
   2550.   5166.   1994.   6790.   3890.   4660.   8990.  12990.   7899.
   6290.    288.    164.    181.    144.    250.    186.    212.    344.
    294.    679.    537.    636.    252.   1284.    579.   1353.    834.
   6387.   2651.   1550.    488.    493.  16990.  14790.   8490.   2184.
   8199.   4687.   7799.   7079.   4330.   5300.   4000.  10000.  10790.
   9190.   3599.   8699.   5149.   4084.   9799.   7690.   4899.   3746.
   4396.    237.    314.    441.    142.]

In [21]:
df["Price"].dtypes

dtype('float64')

In [22]:
df.columns

Index(['Product_name', 'Price', 'Rate', 'Review', 'Summary'], dtype='object')

In [23]:
df["Price"].isna().sum()

np.int64(3)

In [24]:
df= df.dropna(subset=["Price"])

In [25]:
df["Price"].isna().sum()

np.int64(0)

In [26]:
df["Price"].value_counts

<bound method IndexOpsMixin.value_counts of 0         10499.0
1         10499.0
2         10499.0
3         10499.0
4         10499.0
           ...
363255      142.0
363256      142.0
363257      142.0
363258      142.0
363259      142.0
Name: Price, Length: 363242, dtype: float64>

## Rate

In [27]:
df["Rate"].isna().sum()

np.int64(0)

In [28]:
df["Rate"].dtypes

dtype('O')

In [29]:
df["Rate"].unique()

array(['5', '4', '3', '1', '2',
       'Pigeon Favourite Electric Kettle????(1.5 L, Silver, Black)',
       'Bajaj DX 2 L/W Dry Iron',
       'Nova Plus Amaze NI 10 1100 W Dry Iron????(Grey & Turquoise)', 5.0,
       4.0, 1.0, 3.0, 2.0], dtype=object)

In [31]:
df["Rate"] = pd.to_numeric(df["Rate"], errors="coerce")

In [32]:
df["Rate"].isna().sum()

np.int64(3)

In [33]:
df = df.dropna(subset=["Rate"])

In [34]:
df["Rate"].unique()

array([5., 4., 3., 1., 2.])

In [35]:
df["Rate"].dtype

dtype('float64')

In [38]:
df["Rate"].value_counts

<bound method IndexOpsMixin.value_counts of 0         5.0
1         4.0
2         5.0
3         5.0
4         4.0
         ...
363255    5.0
363256    5.0
363257    5.0
363258    5.0
363259    4.0
Name: Rate, Length: 363239, dtype: float64>

## Review

In [39]:
df["Review"].isna().sum()

np.int64(6)

In [40]:
df= df.dropna(subset=["Review"])

In [41]:
df["Review"].isna().sum()

np.int64(0)

In [42]:
df["Review"].dtype

dtype('O')

In [43]:
df["Review"].unique()

array(['Simply awesome',
       'Worth the money . Desert Cooler live up to the Name .',
       'Worth every penny', ..., 'Mast', 'Good in budget', 'Well!!!'],
      shape=(3837,), dtype=object)

## Summary

In [44]:
df["Summary"].isna().sum()

np.int64(2004)

In [45]:
df = df.dropna(subset=["Summary"])

In [46]:
df["Summary"].isna().sum()

np.int64(0)

In [47]:
df["Summary"].dtype

dtype('O')

In [48]:
df["Summary"].unique()

array(["it's really worth every single penny. it works like one ton AC provided that your room has proper ventilation.  I generally keep cooler near to window so that it can pull fresh air from outside and as a result I get very cool air. one more suggestion,  please don't buy cooler which are equipped with a blower fan. Always go for the cooler equipped with metal fan like this one.  In one word, this Compton cooler is Amazing. if you find the review helpful, please thumps up. Happy summer! ????",
       'I bought Crompton Ozone 75 Desert Air Cooler in the Month of May  2018 . Summer at its Peak . I live on top floor so my house gets mare warmer in comparison to other flats . Placed the Air Cooler in Hall near balcony .  The device is elegantly build and performs very well . Crompton has introduced a very good product . Pros:1. Sleek design . 2. water tank excellent .3. Wheel are very good in quality , no problem in mobility even when the tank is full . 4. Child locks in wheel . 5 . Hone...',
       'GREAT packaging by seller. As this was the most important point while transportation from jaipur to Chennai. Secondly Product is quite huge and air throw is very much nearly 13ft at 2 speed  and will give good breeze. Cooling is satisfying due to honeycomb cooling media. No need of filling water daily. Price is high but product is quite satisfactory compared to others. Only drawback is the motor power is 190 w rather than 220w which should be coorected on specs information on flipkart. Good j...',
       ..., 'Best for winter',
       "It's a nice product...thanks very much to Flipcart for the speedy service ???? ???\x8d",
       'Thanks \x9f\x9d???\x8f'], shape=(165842,), dtype=object)

In [49]:
df

,Product_name,Price,Rate,Review,Summary
0,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,5.0,Simply awesome,it's really worth every single penny. it works...
1,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,4.0,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...
2,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,5.0,Worth every penny,GREAT packaging by seller. As this was the mos...
3,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,5.0,Fabulous!,Delivery was delayed by two days except this e...
4,"Crompton 75 L Desert Air Cooler??(White, Tea...",10499.0,4.0,Nice product,A Good cooler by Crompton. The height of the c...
...,...,...,...,...,...
363255,"NIVEA Soft Light Moisturizer for Face, Hand & ...",142.0,5.0,Terrific,Good
363256,"NIVEA Soft Light Moisturizer for Face, Hand & ...",142.0,5.0,Terrific,Thanks
363257,"NIVEA Soft Light Moisturizer for Face, Hand & ...",142.0,5.0,Terrific,Good
363258,"NIVEA Soft Light Moisturizer for Face, Hand & ...",142.0,5.0,Just wow!,Super
363259,"NIVEA Soft Light Moisturizer for Face, Hand & ...",142.0,4.0,Worth the money,Good

In [50]:
df.to_csv("Flipkart_prod_rev_cleaned.csv", index=False)