In [66]:
import pandas as pd
import numpy as np

In [67]:
df= pd.read_csv("C:\\Users\\bhoom\\Downloads\\vgsales.csv")
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [68]:
df.isna().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [70]:
df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [71]:
df=df.drop("Rank", axis = 1)

In [72]:
df.head()

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

## Name

In [73]:
df["Name"].isna().sum()

np.int64(0)

In [74]:
df["Name"].duplicated().sum()

np.int64(5105)

In [75]:
df["Name"].value_counts()

Name
Need for Speed: Most Wanted                12
Ratatouille                                 9
FIFA 14                                     9
LEGO Marvel Super Heroes                    9
Madden NFL 07                               9
                                           ..
Ar tonelico Qoga: Knell of Ar Ciel          1
Galaga: Destination Earth                   1
Nintendo Presents: Crossword Collection     1
TrackMania: Build to Race                   1
Know How 2                                  1
Name: count, Length: 11493, dtype: int64

In [76]:
df = df.drop_duplicates(subset=["Name"], keep="first")

In [77]:
df["Name"].duplicated().sum()

np.int64(0)

In [78]:
df["Name"].value_counts()

Name
Wii Sports                                  1
Ultimate Card Games DS                      1
Savage Skies                                1
Cartoon Network: Punch Time Explosion XL    1
1 vs. 100                                   1
                                           ..
Beyond Good & Evil                          1
Banjo-Kazooie: Grunty's Revenge             1
Bomberman World                             1
The X-Factor                                1
Know How 2                                  1
Name: count, Length: 11493, dtype: int64

In [79]:
df["Name"].unique()

array(['Wii Sports', 'Super Mario Bros.', 'Mario Kart Wii', ...,
       'Plushees', 'Woody Woodpecker in Crazy Castle 5', 'Know How 2'],
      shape=(11493,), dtype=object)

## Platform

In [80]:
df["Platform"].isna().sum()

np.int64(0)

In [81]:
df["Platform"].unique()

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       '3DS', 'PS4', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'GC', 'WiiU',
       'GEN', 'XOne', 'DC', 'SAT', 'PSV', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

In [82]:
df["Platform"].value_counts()

Platform
PS2     1861
DS      1807
PS      1124
Wii      949
PSP      905
PS3      706
GBA      623
X360     559
PC       495
3DS      396
PSV      280
XB       276
N64      246
PS4      241
SNES     229
GC       171
SAT      148
2600     125
NES       90
GB        85
WiiU      55
DC        43
XOne      30
GEN       23
NG         9
SCD        6
WS         4
3DO        3
TG16       2
GG         1
PCFX       1
Name: count, dtype: int64

## Year

In [83]:
df["Year"].isna().sum()

np.int64(165)

In [84]:
df.dropna(subset="Year", inplace=True)

In [85]:
df["Year"].isna().sum()

np.int64(0)

In [86]:
df["Year"].unique()

array([2006., 1985., 2008., 2009., 1996., 1989., 1984., 2005., 1999.,
       2007., 2010., 2013., 2004., 1990., 1988., 2002., 2001., 2011.,
       1998., 2015., 2012., 2014., 1992., 1997., 1993., 1994., 1982.,
       2003., 1986., 2000., 1995., 2016., 1991., 1981., 1987., 1980.,
       1983., 2020., 2017.])

In [87]:
df["Year"].dtypes

dtype('float64')

In [88]:
df["Year"]=df["Year"].astype(int)

In [89]:
df["Year"].dtypes

dtype('int64')

In [90]:
df["Year"].value_counts()

Year
2008    988
2009    959
2010    860
2007    838
2011    747
2006    724
2005    617
2002    565
2004    521
2003    487
2001    410
2012    407
1998    347
2015    333
2000    299
2013    296
1999    292
2014    279
1997    268
1996    247
1995    200
2016    194
1994    111
1993     58
1981     43
1991     40
1992     37
1982     33
1986     21
1983     16
1987     15
1990     14
1989     14
1985     13
1984     13
1988     11
1980      8
2017      2
2020      1
Name: count, dtype: int64

## Genre

In [91]:
df["Genre"].isna().sum()

np.int64(0)

In [92]:
df["Genre"].value_counts()

Genre
Action          1890
Sports          1359
Misc            1313
Role-Playing    1205
Adventure       1040
Shooter          802
Racing           757
Simulation       712
Fighting         605
Platform         580
Strategy         575
Puzzle           490
Name: count, dtype: int64

In [93]:
df["Genre"].unique()

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy'], dtype=object)

## Publisher

In [94]:
df["Publisher"].isna().sum()

np.int64(35)

In [95]:
df.dropna(subset="Publisher", inplace=True)

In [96]:
df["Publisher"].isna().sum()

np.int64(0)

In [97]:
df["Publisher"].value_counts()

Publisher
Namco Bandai Games              756
Nintendo                        656
Konami Digital Entertainment    629
Sony Computer Entertainment     611
Electronic Arts                 593
                               ...
Mitsui                            1
Milestone                         1
Glams                             1
Locus                             1
UIG Entertainment                 1
Name: count, Length: 565, dtype: int64

## NA_Sales

In [98]:
df["NA_Sales"].isna().sum()

np.int64(0)

In [99]:
df["NA_Sales"].value_counts()

NA_Sales
0.00     3635
0.02      355
0.03      347
0.05      330
0.04      328
         ...
2.17        1
2.50        1
1.91        1
3.74        1
41.49       1
Name: count, Length: 386, dtype: int64

In [100]:
df["NA_Sales"].dtypes

dtype('float64')

## EU_Sales

In [101]:
df["EU_Sales"].isna().sum()

np.int64(0)

In [102]:
df["EU_Sales"].value_counts()

EU_Sales
0.00     4511
0.01      853
0.02      752
0.03      533
0.04      448
         ...
2.36        1
1.38        1
1.43        1
3.58        1
29.02       1
Name: count, Length: 286, dtype: int64

In [103]:
df["EU_Sales"].dtypes

dtype('float64')

## JP_Sales

In [104]:
df["JP_Sales"].isna().sum()

np.int64(0)

In [105]:
df["JP_Sales"].value_counts()

JP_Sales
0.00    6147
0.02     593
0.01     472
0.03     431
0.04     319
        ...
1.58       1
2.32       1
3.14       1
2.73       1
2.68       1
Name: count, Length: 242, dtype: int64

In [106]:
df["JP_Sales"].dtypes

dtype('float64')

## Other_Sales

In [107]:
df["Other_Sales"].isna().sum()

np.int64(0)

In [108]:
df["Other_Sales"].value_counts()

Other_Sales
0.00    4727
0.01    2143
0.02    1035
0.03     602
0.04     426
        ...
0.85       1
1.07       1
2.12       1
0.76       1
0.94       1
Name: count, Length: 146, dtype: int64

In [109]:
df["Other_Sales"].dtypes

dtype('float64')

## Global_Sales

In [110]:
df["Global_Sales"].isna().sum()

np.int64(0)

In [111]:
df["Global_Sales"].value_counts()

Global_Sales
0.02     792
0.03     592
0.04     456
0.01     433
0.05     422
        ...
4.79       1
4.83       1
4.84       1
4.87       1
82.74      1
Name: count, Length: 585, dtype: int64

In [112]:
df["Global_Sales"].dtypes

dtype('float64')

In [113]:
df.isna().sum()

Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

In [114]:
df["Name"].duplicated().sum()

np.int64(0)

In [115]:
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16589,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016,Action,dramatic create,0.00,0.00,0.01,0.00,0.01
16590,Eiyuu Densetsu: Sora no Kiseki Material Collec...,PSP,2007,Role-Playing,Falcom Corporation,0.00,0.00,0.01,0.00,0.01
16592,Plushees,DS,2008,Simulation,Destineer,0.01,0.00,0.00,0.00,0.01
16593,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16596,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01

In [116]:
df.to_csv("VideoGame_sales_cleaned.csv", index=False)